from dataclasses import dataclass, field
from typing import Iterable, Iterator, Optional, Union

__all__ = [
    "Color",
    "RGBColorType",
    "HEXColorType",
    "TerminalEffectType",
    "Color",
    "ColoredStr",
    "ColorCode",
    "EffectCode",
    "JapaneseColorCode",
    "ColorTheme",
    "JapaneseColorTheme",
    "EFFECT_CODE",
    "COLOR_CODE",
    "JP_COLOR_CODE",
]


class RGBColorType(tuple):
    def __new__(cls, color: "RGBColorType"):
        assert len(color) == 3, "Color must be a 3-tuple"
        assert all(0 <= c <= 255 for c in color), "Color must be in range 0-255"
        return super().__new__(cls, color)


class HEXColorType(str):
    def __new__(cls, color: str):
        if color.startswith("#"):
            color = color[1:]
        assert len(color) == 6, "Color must be a 6-character string"
        assert all(c in "0123456789abcdef" for c in color.lower()), "Color must be a hexadecimal string"
        return super().__new__(cls, color)


class TerminalEffectType(int):
    def __new__(cls, effect: int = 0):
        assert 0 <= effect <= 9, "Effect must be in range 0-8"
        return super().__new__(cls, effect)


class Color:
    def __init__(
        self,
        color: RGBColorType | HEXColorType | tuple[int, int, int] | str,
        name: Optional[str] = None,
    ):
        if isinstance(color, str):
            color = HEXColorType(color)
        if isinstance(color, tuple):
            color = RGBColorType(color)

        self._rgb = self.convert_any_to_rgb(color)
        self._hex = self.convert_any_to_hex(color)
        self._name = name

    @property
    def name(self) -> Optional[str]:
        return self._name

    @property
    def rgb(self) -> RGBColorType:
        return self._rgb

    @property
    def hex(self) -> HEXColorType:
        return self._hex

    def reverse(self) -> "Color":
        ""
        return Color(tuple(255 - c for c in self.rgb))

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Color):
            raise NotImplementedError
        return self.rgb == other.rgb

    def __repr__(self) -> str:
        s = "Color("
        if self.name:
            s += f'"{self.name}", '
        s += f"RGB:{self.rgb}, HEX:#{self.hex})"
        return s

    def __iter__(self):
        return iter(self.rgb)

    @staticmethod
    def convert_any_to_rgb(
        color: Union[RGBColorType, HEXColorType, tuple[int, int, int], str],
    ) -> RGBColorType:
        if isinstance(color, tuple):
            return RGBColorType(color)
        elif isinstance(color, str):
            rgb: tuple[int, int, int] = tuple(int(color[i : i + 2], 16) for i in range(0, 6, 2))  # type: ignore
            assert len(rgb) == 3, "Color must be a 3-tuple"
            return RGBColorType(rgb)
        else:
            return color

    @staticmethod
    def convert_any_to_hex(
        color: Union[RGBColorType, HEXColorType, tuple[int, int, int], str],
    ) -> HEXColorType:
        if isinstance(color, tuple):
            return HEXColorType("".join(f"{c:02x}" for c in color))
        elif isinstance(color, str):
            return HEXColorType(color)
        else:
            return color


class ColoredStr:
    """Decorate a string with color and effects for terminal output.
    ColoredStr is a subclass of str that allows you to create colored text in the terminal.

    Args:
        text (str): The text to be colored.
        fg (Color, optional): The foreground color of the text. Defaults to None.
        bg (Color, optional): The background color of the text. Defaults to None.
        effects (Union[TerminalEffectType, int, Iterable[TerminalEffectType], Iterable[int]], optional): The effects to be applied to the text. Defaults to None.
        foreground_color (Color, optional): The foreground color of the text. Defaults to None.
        background_color (Color, optional): The background color of the text. Defaults to None.

    Returns:
        ColoredStr: The colored text.

    Examples:
        >>> text = ColoredStr("Hello, World!", ColorCode.GREEN)
        >>> print(text)
        Hello, World! # green text

        >>> text = ColoredStr("Hello, World!", ColorCode.RED, ColorCode.BLACK)
        >>> print(text)
        Hello, World! # red text on black background

        >>> text = ColoredStr("Hello, World!", bg=ColorCode.GREEN, effects=EffectCode.BOLD)
        >>> print(text)
        Hello, World! # green text with bold effect

        >>> text = ColoredStr("Hello, World!", fg=ColorCode.RED, bg=ColorCode.BLACK, effects=[EffectCode.BOLD, EffectCode.UNDERLINE, EffectCode.ITALIC])
        >>> print(text)
        Hello, World! # red text on black background with bold, underline, and italic effects

        >>> text = ColoredStr("Hello, World!", foreground_color=ColorCode.RED, background_color=ColorCode.BLACK, effects=[1, 4, 3])
        >>> print(text)
        Hello, World! # red text on black background with bold, underline, and italic effects

    """

    def __init__(
        self,
        text: str,
        fg: Optional[Color] = None,
        bg: Optional[Color] = None,
        *,
        effects: Optional[TerminalEffectType | int | Iterable[TerminalEffectType] | Iterable[int]] = None,
        foreground_color: Optional[Color] = None,
        background_color: Optional[Color] = None,
    ):
        if fg:
            foreground_color = fg
        if bg:
            background_color = bg
        self._foreground = ""
        self._background = ""
        self._inner_text = text
        if foreground_color:
            if not isinstance(foreground_color, Color):
                foreground_color = Color(self.convert_any_to_rgb(foreground_color))
        if effects:
            if not isinstance(effects, Iterable):
                effects = [effects]
            effects = [str(TerminalEffectType(e)) for e in effects if isinstance(e, int)]
            if foreground_color:
                r, g, b = foreground_color.rgb
                self._foreground = f"\033[{';'.join(effects)};38;2;{r};{g};{b}m"
        else:
            if foreground_color:
                r, g, b = foreground_color.rgb
                self._foreground = f"\033[38;2;{r};{g};{b}m"

        if background_color:
            if not isinstance(background_color, Color):
                background_color = Color(self.convert_any_to_rgb(background_color))
            r, g, b = background_color.rgb
            self._background = f"\033[48;2;{r};{g};{b}m"

        self._reset = "\033[0m"

    @property
    def text(self) -> str:
        return self._inner_text

    def __len__(self) -> int:
        return len(self._inner_text)

    def __str__(self) -> str:
        return f"{self._foreground}{self._background}{self._inner_text}{self._reset}{self._reset}"

    def __add__(self, other: str) -> str:
        return str(self) + str(other)

    def __radd__(self, other: str) -> str:
        return str(other) + str(self)

    @staticmethod
    def convert_any_to_rgb(color: Color) -> Color:
        if isinstance(color, tuple):
            return RGBColorType(color)
        elif isinstance(color, str):
            return RGBColorType(tuple(int(color[i : i + 2], 16) for i in range(0, 6, 2)))
        else:
            return color


@dataclass(frozen=True)
class EffectCode:
    BOLD: TerminalEffectType = field(default_factory=lambda: TerminalEffectType(1))
    FAINT: TerminalEffectType = field(default_factory=lambda: TerminalEffectType(2))
    ITALIC: TerminalEffectType = field(default_factory=lambda: TerminalEffectType(3))
    UNDERLINE: TerminalEffectType = field(default_factory=lambda: TerminalEffectType(4))
    BLINK: TerminalEffectType = field(default_factory=lambda: TerminalEffectType(5))
    RAPID_BLINK: TerminalEffectType = field(default_factory=lambda: TerminalEffectType(6))
    REVERSE: TerminalEffectType = field(default_factory=lambda: TerminalEffectType(7))
    INVISIBLE: TerminalEffectType = field(default_factory=lambda: TerminalEffectType(8))
    STRIKE: TerminalEffectType = field(default_factory=lambda: TerminalEffectType(9))


EFFECT_CODE = EffectCode()


def colorfield(*args):
    return field(default_factory=lambda: Color(*args))


@dataclass(frozen=True, slots=True)
class ColorCode:
    BLACK: Color = colorfield("#000000", "black")
    DIMGRAY: Color = colorfield("#696969", "dimgray")
    GRAY: Color = colorfield("#808080", "gray")
    DARKGRAY: Color = colorfield("#A9A9A9", "darkgray")
    SILVER: Color = colorfield("#C0C0C0", "silver")
    LIGHTGRAY: Color = colorfield("#D3D3D3", "lightgray")
    GAINSBORO: Color = colorfield("#DCDCDC", "gainsboro")
    WHITESMOKE: Color = colorfield("#F5F5F5", "whitesmoke")
    WHITE: Color = colorfield("#FFFFFF", "white")
    SNOW: Color = colorfield("#FFFAFA", "snow")
    GHOSTWHITE: Color = colorfield("#F8F8FF", "ghostwhite")
    FLORALWHITE: Color = colorfield("#FFFAF0", "floralwhite")
    LINEN: Color = colorfield("#FAF0E6", "linen")
    ANTIQUEWHITE: Color = colorfield("#FAEBD7", "antiquewhite")
    PAPAYAWHIP: Color = colorfield("#FFEFD5", "papayawhip")
    BLANCHEDALMOND: Color = colorfield("#FFEBCD", "blanchedalmond")
    BISQUE: Color = colorfield("#FFE4C4", "bisque")
    MOCASSIN: Color = colorfield("#FFE4B5", "mocassin")
    NAVAJOWHITE: Color = colorfield("#FFDEAD", "navajowhite")
    PEACHPUFF: Color = colorfield("#FFDAB9", "peachpuff")
    MISTYROSE: Color = colorfield("#FFE4E1", "mistyrose")
    LAVENDERBLUSH: Color = colorfield("#FFF0F5", "lavenderblush")
    SEASHELL: Color = colorfield("#FFF5EE", "seashell")
    OLDLACE: Color = colorfield("#FDF5E6", "oldlace")
    IVORY: Color = colorfield("#FFFFF0", "ivory")
    HONEYDEW: Color = colorfield("#F0FFF0", "honeydew")
    MINTCREAM: Color = colorfield("#F5FFFA", "mintcream")
    AZURE: Color = colorfield("#F0FFFF", "azure")
    ALICEBLUE: Color = colorfield("#F0F8FF", "aliceblue")
    LAVENDER: Color = colorfield("#E6E6FA", "lavender")
    LIGHTSTEELBLUE: Color = colorfield("#B0C4DE", "lightsteelblue")
    LIGHTSLATEGRAY: Color = colorfield("#778899", "lightslategray")
    SLATEGRAY: Color = colorfield("#708090", "slategray")
    STEELBLUE: Color = colorfield("#4682B4", "steelblue")
    ROYALBLUE: Color = colorfield("#4169E1", "royalblue")
    MIDNIGHTBLUE: Color = colorfield("#191970", "midnightblue")
    NAVY: Color = colorfield("#000080", "navy")
    DARKBLUE: Color = colorfield("#00008B", "darkblue")
    MEDIUMBLUE: Color = colorfield("#0000CD", "mediumblue")
    BLUE: Color = colorfield("#0000FF", "blue")
    DODGERBLUE: Color = colorfield("#1E90FF", "dodgerblue")
    CORNFLOWERBLUE: Color = colorfield("#6495ED", "cornflowerblue")
    DEEPSKYBLUE: Color = colorfield("#00BFFF", "deepskyblue")
    LIGHTSKYBLUE: Color = colorfield("#87CEFA", "lightskyblue")
    SKYBLUE: Color = colorfield("#87CEEB", "skyblue")
    LIGHTBLUE: Color = colorfield("#ADD8E6", "lightblue")
    POWDERBLUE: Color = colorfield("#B0E0E6", "powderblue")
    PALETURQUOISE: Color = colorfield("#AFEEEE", "paleturquoise")
    LIGHTCYAN: Color = colorfield("#E0FFFF", "lightcyan")
    CYAN: Color = colorfield("#00FFFF", "cyan")
    AQUA: Color = colorfield("#00FFFF", "aqua")  # same as cyan
    TURQUOISE: Color = colorfield("#40E0D0", "turquoise")
    MEDIUMTURQUOISE: Color = colorfield("#48D1CC", "mediumturquoise")
    DARKTURQUOISE: Color = colorfield("#00CED1", "darkturquoise")
    LIGHTSEAGREEN: Color = colorfield("#20B2AA", "lightseagreen")
    CADETBLUE: Color = colorfield("#5F9EA0", "cadetblue")
    DARKCYAN: Color = colorfield("#008B8B", "darkcyan")
    TEAL: Color = colorfield("#008080", "teal")
    DARKSLATEGRAY: Color = colorfield("#2F4F4F", "darkslategray")
    DARKGREEN: Color = colorfield("#006400", "darkgreen")
    GREEN: Color = colorfield("#008000", "green")
    FORESTGREEN: Color = colorfield("#228B22", "forestgreen")
    SEAGREEN: Color = colorfield("#2E8B57", "seagreen")
    MEDIUMSEAGREEN: Color = colorfield("#3CB371", "mediumseagreen")
    MEDIUMAQUAMARINE: Color = colorfield("#66CDAA", "mediumaquamarine")
    DARKSEARGREEN: Color = colorfield("#8FBC8F", "darkseagreen")
    AQUAMARINE: Color = colorfield("#7FFFD4", "aquamarine")
    PALEGREEN: Color = colorfield("#98FB98", "palegreen")
    LIGHTGREEN: Color = colorfield("#90EE90", "lightgreen")
    SPRINGGREEN: Color = colorfield("#00FF7F", "springgreen")
    MEDIUMSPRINGGREEN: Color = colorfield("#00FA9A", "mediumspringgreen")
    LAWNGREEN: Color = colorfield("#7CFC00", "lawngreen")
    CHARTREUSE: Color = colorfield("#7FFF00", "chartreuse")
    GREENYELLOW: Color = colorfield("#ADFF2F", "greenyellow")
    LIME: Color = colorfield("#00FF00", "lime")
    LIMEGREEN: Color = colorfield("#32CD32", "limegreen")
    YELLOWGREEN: Color = colorfield("#9ACD32", "yellowgreen")
    DARKOLIVEGREEN: Color = colorfield("#556B2F", "darkolivegreen")
    OLIVEDRAB: Color = colorfield("#6B8E23", "olivedrab")
    OLIVE: Color = colorfield("#808000", "olive")
    DARKKHAKI: Color = colorfield("#BDB76B", "darkkhaki")
    PALEGOLDENROD: Color = colorfield("#EEE8AA", "palegoldenrod")
    CORNSILK: Color = colorfield("#FFF8DC", "cornsilk")
    BEIGE: Color = colorfield("#F5F5DC", "beige")
    LIGHTYELLOW: Color = colorfield("#FFFFE0", "lightyellow")
    LIGHTGOLDENRODYELLOW: Color = colorfield("#FAFAD2", "lightgoldenrodyellow")
    LEMONCHIFFON: Color = colorfield("#FFFACD", "lemonchiffon")
    WHEAT: Color = colorfield("#F5DEB3", "wheat")
    BURLYWOOD: Color = colorfield("#DEB887", "burlywood")
    TAN: Color = colorfield("#D2B48C", "tan")
    KHAKI: Color = colorfield("#F0E68C", "khaki")
    YELLOW: Color = colorfield("#FFFF00", "yellow")
    GOLD: Color = colorfield("#FFD700", "gold")
    ORANGE: Color = colorfield("#FFA500", "orange")
    SANDYBROWN: Color = colorfield("#F4A460", "sandybrown")
    DARKORANGE: Color = colorfield("#FF8C00", "darkorange")
    GOLDENROD: Color = colorfield("#DAA520", "goldenrod")
    PERU: Color = colorfield("#CD853F", "peru")
    DARKGOLDENROD: Color = colorfield("#B8860B", "darkgoldenrod")
    CHOCOLATE: Color = colorfield("#D2691E", "chocolate")
    SIENNA: Color = colorfield("#A0522D", "sienna")
    SADDLEBROWN: Color = colorfield("#8B4513", "saddlebrown")
    MAROON: Color = colorfield("#800000", "maroon")
    DARKRED: Color = colorfield("#8B0000", "darkred")
    BROWN: Color = colorfield("#A52A2A", "brown")
    FIREBRICK: Color = colorfield("#B22222", "firebrick")
    INDIANRED: Color = colorfield("#CD5C5C", "indianred")
    ROSYBROWN: Color = colorfield("#BC8F8F", "rosybrown")
    DARKSALMON: Color = colorfield("#E9967A", "darksalmon")
    LIGHTCORAL: Color = colorfield("#F08080", "lightcoral")
    SALMON: Color = colorfield("#FA8072", "salmon")
    LIGHTSALMON: Color = colorfield("#FFA07A", "lightsalmon")
    CORAL: Color = colorfield("#FF7F50", "coral")
    TOMATO: Color = colorfield("#FF6347", "tomato")
    ORANGERED: Color = colorfield("#FF4500", "orangered")
    RED: Color = colorfield("#FF0000", "red")
    CRIMSON: Color = colorfield("#DC143C", "crimson")
    MEDIUMVIOLETRED: Color = colorfield("#C71585", "mediumvioletred")
    DEEPPINK: Color = colorfield("#FF1493", "deeppink")
    HOTPINK: Color = colorfield("#FF69B4", "hotpink")
    PALEVIOLETRED: Color = colorfield("#DB7093", "palevioletred")
    PINK: Color = colorfield("#FFC0CB", "pink")
    LIGHTPINK: Color = colorfield("#FFB6C1", "lightpink")
    THISTLE: Color = colorfield("#D8BFD8", "thistle")
    MAGENTA: Color = colorfield("#FF00FF", "magenta")  # same as fuchsia
    FUCHSIA: Color = colorfield("#FF00FF", "fuchsia")  # same as magenta
    VIOLET: Color = colorfield("#EE82EE", "violet")
    PLUM: Color = colorfield("#DDA0DD", "plum")
    ORCHID: Color = colorfield("#DA70D6", "orchid")
    MEDIUMORCHID: Color = colorfield("#BA55D3", "mediumorchid")
    DARKORCHID: Color = colorfield("#9932CC", "darkorchid")
    DARKVIOLET: Color = colorfield("#9400D3", "darkviolet")
    DARKMAGENTA: Color = colorfield("#8B008B", "darkmagenta")
    PURPLE: Color = colorfield("#800080", "purple")
    INDIGO: Color = colorfield("#4B0082", "indigo")
    DARKSLATEBLUE: Color = colorfield("#483D8B", "darkslateblue")
    BLUEVIOLET: Color = colorfield("#8A2BE2", "blueviolet")
    MEDIUMPURPLE: Color = colorfield("#9370DB", "mediumpurple")
    SLATEBLUE: Color = colorfield("#6A5ACD", "slateblue")
    MEDIUMSLATEBLUE: Color = colorfield("#7B68EE", "mediumslateblue")

    @staticmethod
    def search(name: str) -> Color:
        if getattr(ColorCode, name, None):
            return getattr(ColorCode, name)
        else:
            candidate = []
            for slot in ColorCode.__slots__:
                if name.lower() in slot.lower():
                    candidate.append(slot)
            if len(candidate) == 1:
                return getattr(ColorCode, candidate[0])
            elif len(candidate) > 1:
                raise AttributeError(f"Color '{name}' is ambiguous, candidates are {candidate}")
            raise AttributeError(f"Color '{name}' not found")


COLOR_CODE = ColorCode()


@dataclass(frozen=True, slots=True)
class JapaneseColorCode:
    # https://www.colordic.org/w
    桜色: Color = colorfield("#FEF4F4", "桜色")
    小豆色: Color = colorfield("#96514D", "小豆色")
    黄金: Color = colorfield("#E6B422", "黄金")
    萌葱色: Color = colorfield("#006E54", "萌葱色")
    古代紫: Color = colorfield("#895B8A", "古代紫")
    薄桜: Color = colorfield("#FDEFF2", "薄桜")
    枯茶: Color = colorfield("#8D6449", "枯茶")
    櫨染: Color = colorfield("#D9A62E", "櫨染")
    花緑青: Color = colorfield("#00A381", "花緑青")
    茄子紺: Color = colorfield("#824880", "茄子紺")
    桜鼠: Color = colorfield("#E9DFE5", "桜鼠")
    飴色: Color = colorfield("#DEB068", "飴色")
    黄朽葉色: Color = colorfield("#D3A243", "黄朽葉色")
    翡翠色: Color = colorfield("#38B48B", "翡翠色")
    二藍: Color = colorfield("#915C8B", "二藍")
    鴇鼠: Color = colorfield("#E4D2D8", "鴇鼠")
    駱駝色: Color = colorfield("#BF794E", "駱駝色")
    山吹茶: Color = colorfield("#C89932", "山吹茶")
    青緑: Color = colorfield("#00A497", "青緑")
    京紫: Color = colorfield("#9D5B8B", "京紫")
    虹色: Color = colorfield("#F6BFBC", "虹色")
    土色: Color = colorfield("#BC763C", "土色")
    芥子色: Color = colorfield("#D0AF4C", "芥子色")
    水浅葱: Color = colorfield("#80ABA9", "水浅葱")
    蒲葡: Color = colorfield("#7A4171", "蒲葡")
    珊瑚色: Color = colorfield("#F5B1AA", "珊瑚色")
    黄唐茶: Color = colorfield("#B98C46", "黄唐茶")
    豆がら茶: Color = colorfield("#8B968D", "豆がら茶")
    錆浅葱: Color = colorfield("#5C9291", "錆浅葱")
    若紫: Color = colorfield("#BC64A4", "若紫")
    一斤染: Color = colorfield("#F5B199", "一斤染")
    桑染: Color = colorfield("#B79B5B", "桑染")
    麹塵: Color = colorfield("#6E7955", "麹塵")
    青碧: Color = colorfield("#478384", "青碧")
    紅紫: Color = colorfield("#B44C97", "紅紫")
    宍色: Color = colorfield("#EFAB93", "宍色")
    櫨色: Color = colorfield("#B77B57", "櫨色")
    山鳩色: Color = colorfield("#767C6B", "山鳩色")
    御召茶: Color = colorfield("#43676B", "御召茶")
    梅紫: Color = colorfield("#AA4C8F", "梅紫")
    紅梅色: Color = colorfield("#F2A0A1", "紅梅色")
    黄橡: Color = colorfield("#B68D4C", "黄橡")
    利休鼠: Color = colorfield("#888E7E", "利休鼠")
    湊鼠: Color = colorfield("#80989B", "湊鼠")
    菖蒲色: Color = colorfield("#CC7EB1", "菖蒲色")
    薄紅: Color = colorfield("#F0908D", "薄紅")
    丁字染: Color = colorfield("#AD7D4C", "丁字染")
    海松茶: Color = colorfield("#5A544B", "海松茶")
    高麗納戸: Color = colorfield("#2C4F54", "高麗納戸")
    紅藤色: Color = colorfield("#CCA6BF", "紅藤色")
    甚三紅: Color = colorfield("#EE827C", "甚三紅")
    香染: Color = colorfield("#AD7D4C", "香染")
    藍海松茶: Color = colorfield("#56564B", "藍海松茶")
    百入茶: Color = colorfield("#1F3134", "百入茶")
    浅紫: Color = colorfield("#C4A3BF", "浅紫")
    桃色: Color = colorfield("#F09199", "桃色")
    枇杷茶: Color = colorfield("#AE7C4F", "枇杷茶")
    藍媚茶: Color = colorfield("#555647", "藍媚茶")
    錆鼠: Color = colorfield("#47585C", "錆鼠")
    紫水晶: Color = colorfield("#E7E7EB", "紫水晶")
    鴇色: Color = colorfield("#F4B3C2", "鴇色")
    芝翫茶: Color = colorfield("#AD7E4E", "芝翫茶")
    千歳茶: Color = colorfield("#494A41", "千歳茶")
    錆鉄御納戸: Color = colorfield("#485859", "錆鉄御納戸")
    薄梅鼠: Color = colorfield("#DCD6D9", "薄梅鼠")
    撫子色: Color = colorfield("#EEBBCB", "撫子色")
    焦香: Color = colorfield("#AE7C58", "焦香")
    岩井茶: Color = colorfield("#6B6F59", "岩井茶")
    藍鼠: Color = colorfield("#6C848D", "藍鼠")
    暁鼠: Color = colorfield("#D3CFD9", "暁鼠")
    灰梅: Color = colorfield("#E8D3C7", "灰梅")
    胡桃色: Color = colorfield("#A86F4C", "胡桃色")
    仙斎茶: Color = colorfield("#474B42", "仙斎茶")
    錆御納戸: Color = colorfield("#53727D", "錆御納戸")
    牡丹鼠: Color = colorfield("#D3CCD6", "牡丹鼠")
    灰桜: Color = colorfield("#E8D3D1", "灰桜")
    渋紙色: Color = colorfield("#946243", "渋紙色")
    黒緑: Color = colorfield("#333631", "黒緑")
    舛花色: Color = colorfield("#5B7E91", "舛花色")
    霞色: Color = colorfield("#C8C2C6", "霞色")
    淡紅藤: Color = colorfield("#E6CDE3", "淡紅藤")
    朽葉色: Color = colorfield("#917347", "朽葉色")
    柳煤竹: Color = colorfield("#5B6356", "柳煤竹")
    熨斗目花色: Color = colorfield("#426579", "熨斗目花色")
    藤鼠: Color = colorfield("#A6A5C4", "藤鼠")
    石竹色: Color = colorfield("#E5ABBE", "石竹色")
    桑茶: Color = colorfield("#956F29", "桑茶")
    樺茶色: Color = colorfield("#726250", "樺茶色")
    御召御納戸: Color = colorfield("#4C6473", "御召御納戸")
    半色: Color = colorfield("#A69ABD", "半色")
    薄紅梅: Color = colorfield("#E597B2", "薄紅梅")
    路考茶: Color = colorfield("#8C7042", "路考茶")
    空五倍子色: Color = colorfield("#9D896C", "空五倍子色")
    鉄御納戸: Color = colorfield("#455765", "鉄御納戸")
    薄色: Color = colorfield("#A89DAC", "薄色")
    桃花色: Color = colorfield("#E198B4", "桃花色")
    国防色: Color = colorfield("#7B6C3E", "国防色")
    生壁色: Color = colorfield("#94846A", "生壁色")
    紺鼠: Color = colorfield("#44617B", "紺鼠")
    薄鼠: Color = colorfield("#9790A4", "薄鼠")
    水柿: Color = colorfield("#E4AB9B", "水柿")
    伽羅色: Color = colorfield("#D8A373", "伽羅色")
    肥後煤竹: Color = colorfield("#897858", "肥後煤竹")
    藍鉄: Color = colorfield("#393F4C", "藍鉄")
    鳩羽鼠: Color = colorfield("#9E8B8E", "鳩羽鼠")
    ときがら茶: Color = colorfield("#E09E87", "ときがら茶")
    江戸茶: Color = colorfield("#CD8C5C", "江戸茶")
    媚茶: Color = colorfield("#716246", "媚茶")
    青褐: Color = colorfield("#393E4F", "青褐")
    鳩羽色: Color = colorfield("#95859C", "鳩羽色")
    退紅: Color = colorfield("#D69090", "退紅")
    樺色: Color = colorfield("#CD5E3C", "樺色")
    白橡: Color = colorfield("#CBB994", "白橡")
    褐返: Color = colorfield("#203744", "褐返")
    桔梗鼠: Color = colorfield("#95949A", "桔梗鼠")
    薄柿: Color = colorfield("#D4ACAD", "薄柿")
    紅鬱金: Color = colorfield("#CB8347", "紅鬱金")
    亜麻色: Color = colorfield("#D6C6AF", "亜麻色")
    褐色: Color = colorfield("#4D4C61", "褐色")
    紫鼠: Color = colorfield("#71686C", "紫鼠")
    長春色: Color = colorfield("#C97586", "長春色")
    土器色: Color = colorfield("#C37854", "土器色")
    榛色: Color = colorfield("#BFA46F", "榛色")
    月白: Color = colorfield("#EAF4FC", "月白")
    葡萄鼠: Color = colorfield("#705B67", "葡萄鼠")
    梅鼠: Color = colorfield("#C099A0", "梅鼠")
    狐色: Color = colorfield("#C38743", "狐色")
    灰汁色: Color = colorfield("#9E9478", "灰汁色")
    白菫色: Color = colorfield("#EAEDF7", "白菫色")
    濃色: Color = colorfield("#634950", "濃色")
    鴇浅葱: Color = colorfield("#B88884", "鴇浅葱")
    黄土色: Color = colorfield("#C39143", "黄土色")
    利休茶: Color = colorfield("#A59564", "利休茶")
    白花色: Color = colorfield("#E8ECEF", "白花色")
    紫鳶: Color = colorfield("#5F414B", "紫鳶")
    梅染: Color = colorfield("#B48A76", "梅染")
    琥珀色: Color = colorfield("#BF783A", "琥珀色")
    鶯茶: Color = colorfield("#715C1F", "鶯茶")
    藍白: Color = colorfield("#EBF6F7", "藍白")
    濃鼠: Color = colorfield("#4F455C", "濃鼠")
    蘇芳香: Color = colorfield("#A86965", "蘇芳香")
    赤茶: Color = colorfield("#BB5535", "赤茶")
    木蘭色: Color = colorfield("#C7B370", "木蘭色")
    白藍: Color = colorfield("#C1E4E9", "白藍")
    藤煤竹: Color = colorfield("#5A5359", "藤煤竹")
    浅蘇芳: Color = colorfield("#A25768", "浅蘇芳")
    代赭: Color = colorfield("#BB5520", "代赭")
    砂色: Color = colorfield("#DCD3B2", "砂色")
    水色: Color = colorfield("#BCE2E8", "水色")
    滅紫: Color = colorfield("#594255", "滅紫")
    真朱: Color = colorfield("#EC6D71", "真朱")
    煉瓦色: Color = colorfield("#B55233", "煉瓦色")
    油色: Color = colorfield("#A19361", "油色")
    瓶覗: Color = colorfield("#A2D7DD", "瓶覗")
    紅消鼠: Color = colorfield("#524748", "紅消鼠")
    赤紫: Color = colorfield("#EB6EA5", "赤紫")
    雀茶: Color = colorfield("#AA4F37", "雀茶")
    利休色: Color = colorfield("#8F8667", "利休色")
    秘色色: Color = colorfield("#ABCED8", "秘色色")
    似せ紫: Color = colorfield("#513743", "似せ紫")
    躑躅色: Color = colorfield("#E95295", "躑躅色")
    団十郎茶: Color = colorfield("#9F563A", "団十郎茶")
    梅幸茶: Color = colorfield("#887938", "梅幸茶")
    空色: Color = colorfield("#A0D8EF", "空色")
    灰黄緑: Color = colorfield("#E6EAE3", "灰黄緑")
    牡丹色: Color = colorfield("#E7609E", "牡丹色")
    柿渋色: Color = colorfield("#9F563A", "柿渋色")
    璃寛茶: Color = colorfield("#6A5D21", "璃寛茶")
    勿忘草色: Color = colorfield("#89C3EB", "勿忘草色")
    蕎麦切色: Color = colorfield("#D4DCD6", "蕎麦切色")
    今様色: Color = colorfield("#D0576B", "今様色")
    紅鳶: Color = colorfield("#9A493F", "紅鳶")
    黄海松茶: Color = colorfield("#918754", "黄海松茶")
    青藤色: Color = colorfield("#84A2D4", "青藤色")
    薄雲鼠: Color = colorfield("#D4DCDA", "薄雲鼠")
    中紅: Color = colorfield("#C85179", "中紅")
    灰茶: Color = colorfield("#98623C", "灰茶")
    菜種油色: Color = colorfield("#A69425", "菜種油色")
    白群: Color = colorfield("#83CCD2", "白群")
    枯野色: Color = colorfield("#D3CBC6", "枯野色")
    薔薇色: Color = colorfield("#E9546B", "薔薇色")
    茶色: Color = colorfield("#965042", "茶色")
    青朽葉: Color = colorfield("#ADA250", "青朽葉")
    浅縹: Color = colorfield("#84B9CB", "浅縹")
    潤色: Color = colorfield("#C8C2BE", "潤色")
    韓紅: Color = colorfield("#E95464", "韓紅")
    檜皮色: Color = colorfield("#965036", "檜皮色")
    根岸色: Color = colorfield("#938B4B", "根岸色")
    薄花色: Color = colorfield("#698AAB", "薄花色")
    利休白茶: Color = colorfield("#B3ADA0", "利休白茶")
    銀朱: Color = colorfield("#C85554", "銀朱")
    鳶色: Color = colorfield("#95483F", "鳶色")
    鶸茶: Color = colorfield("#8C8861", "鶸茶")
    納戸色: Color = colorfield("#008899", "納戸色")
    茶鼠: Color = colorfield("#A99E93", "茶鼠")
    赤紅: Color = colorfield("#C53D43", "赤紅")
    柿茶: Color = colorfield("#954E2A", "柿茶")
    柳茶: Color = colorfield("#A1A46D", "柳茶")
    浅葱色: Color = colorfield("#00A3AF", "浅葱色")
    胡桃染: Color = colorfield("#A58F86", "胡桃染")
    紅緋: Color = colorfield("#E83929", "紅緋")
    弁柄色: Color = colorfield("#8F2E14", "弁柄色")
    海松色: Color = colorfield("#726D40", "海松色")
    花浅葱: Color = colorfield("#2A83A2", "花浅葱")
    江戸鼠: Color = colorfield("#928178", "江戸鼠")
    赤: Color = colorfield("#E60033", "赤")
    赤錆色: Color = colorfield("#8A3319", "赤錆色")
    鶯色: Color = colorfield("#928C36", "鶯色")
    新橋色: Color = colorfield("#59B9C6", "新橋色")
    煤色: Color = colorfield("#887F7A", "煤色")
    猩々緋: Color = colorfield("#E2041B", "猩々緋")
    褐色: Color = colorfield("#8A3B00", "褐色")
    緑黄色: Color = colorfield("#DCCB18", "緑黄色")
    天色: Color = colorfield("#2CA9E1", "天色")
    丁子茶: Color = colorfield("#B4866B", "丁子茶")
    紅: Color = colorfield("#D7003A", "紅")
    栗梅: Color = colorfield("#852E19", "栗梅")
    鶸色: Color = colorfield("#D7CF3A", "鶸色")
    露草色: Color = colorfield("#38A1DB", "露草色")
    柴染: Color = colorfield("#B28C6E", "柴染")
    深緋: Color = colorfield("#C9171E", "深緋")
    紅檜皮: Color = colorfield("#7B4741", "紅檜皮")
    抹茶色: Color = colorfield("#C5C56A", "抹茶色")
    青: Color = colorfield("#0095D9", "青")
    宗伝唐茶: Color = colorfield("#A16D5D", "宗伝唐茶")
    緋色: Color = colorfield("#D3381C", "緋色")
    海老茶: Color = colorfield("#773C30", "海老茶")
    若草色: Color = colorfield("#C3D825", "若草色")
    薄藍: Color = colorfield("#0094C8", "薄藍")
    砺茶: Color = colorfield("#9F6F55", "砺茶")
    赤丹: Color = colorfield("#CE5242", "赤丹")
    唐茶: Color = colorfield("#783C1D", "唐茶")
    黄緑: Color = colorfield("#B8D200", "黄緑")
    縹色: Color = colorfield("#2792C3", "縹色")
    煎茶色: Color = colorfield("#8C6450", "煎茶色")
    紅赤: Color = colorfield("#D9333F", "紅赤")
    栗色: Color = colorfield("#762F07", "栗色")
    若芽色: Color = colorfield("#E0EBAF", "若芽色")
    紺碧: Color = colorfield("#007BBB", "紺碧")
    銀煤竹: Color = colorfield("#856859", "銀煤竹")
    臙脂: Color = colorfield("#B94047", "臙脂")
    赤銅色: Color = colorfield("#752100", "赤銅色")
    若菜色: Color = colorfield("#D8E698", "若菜色")
    薄群青: Color = colorfield("#5383C3", "薄群青")
    黄枯茶: Color = colorfield("#765C47", "黄枯茶")
    朱緋: Color = colorfield("#BA2636", "朱・緋")
    錆色: Color = colorfield("#6C3524", "錆色")
    若苗色: Color = colorfield("#C7DC68", "若苗色")
    薄花桜: Color = colorfield("#5A79BA", "薄花桜")
    煤竹色: Color = colorfield("#6F514C", "煤竹色")
    茜色: Color = colorfield("#B7282E", "茜色")
    赤褐色: Color = colorfield("#683F36", "赤褐色")
    青丹: Color = colorfield("#99AB4E", "青丹")
    群青色: Color = colorfield("#4C6CB3", "群青色")
    焦茶: Color = colorfield("#6F4B3E", "焦茶")
    紅海老茶: Color = colorfield("#A73836", "紅海老茶")
    茶褐色: Color = colorfield("#664032", "茶褐色")
    草色: Color = colorfield("#7B8D42", "草色")
    杜若色: Color = colorfield("#3E62AD", "杜若色")
    黒橡: Color = colorfield("#544A47", "黒橡")
    蘇芳: Color = colorfield("#9E3D3F", "蘇芳")
    栗皮茶: Color = colorfield("#6D3C32", "栗皮茶")
    苔色: Color = colorfield("#69821B", "苔色")
    瑠璃色: Color = colorfield("#1E50A2", "瑠璃色")
    憲法色: Color = colorfield("#543F32", "憲法色")
    真紅: Color = colorfield("#A22041", "真紅")
    黒茶: Color = colorfield("#583822", "黒茶")
    萌黄: Color = colorfield("#AACF53", "萌黄")
    薄縹: Color = colorfield("#507EA4", "薄縹")
    涅色: Color = colorfield("#554738", "涅色")
    濃紅: Color = colorfield("#A22041", "濃紅")
    葡萄茶: Color = colorfield("#6C2C2F", "葡萄茶")
    苗色: Color = colorfield("#B0CA71", "苗色")
    瑠璃紺: Color = colorfield("#19448E", "瑠璃紺")
    檳榔子染: Color = colorfield("#433D3C", "檳榔子染")
    象牙色: Color = colorfield("#F8F4E6", "象牙色")
    葡萄色: Color = colorfield("#640125", "葡萄色")
    若葉色: Color = colorfield("#B9D08B", "若葉色")
    紺瑠璃: Color = colorfield("#164A84", "紺瑠璃")
    黒鳶: Color = colorfield("#432F2F", "黒鳶")
    練色: Color = colorfield("#EDE4CD", "練色")
    萱草色: Color = colorfield("#F8B862", "萱草色")
    松葉色: Color = colorfield("#839B5C", "松葉色")
    藍色: Color = colorfield("#165E83", "藍色")
    赤墨: Color = colorfield("#3F312B", "赤墨")
    灰白色: Color = colorfield("#E9E4D4", "灰白色")
    柑子色: Color = colorfield("#F6AD49", "柑子色")
    夏虫色: Color = colorfield("#CEE4AE", "夏虫色")
    青藍: Color = colorfield("#274A78", "青藍")
    黒紅: Color = colorfield("#302833", "黒紅")
    蒸栗色: Color = colorfield("#EBE1A9", "蒸栗色")
    金茶: Color = colorfield("#F39800", "金茶")
    鶸萌黄: Color = colorfield("#82AE46", "鶸萌黄")
    深縹: Color = colorfield("#2A4073", "深縹")
    白: Color = colorfield("#FFFFFF", "白")
    女郎花: Color = colorfield("#F2F2B0", "女郎花")
    蜜柑色: Color = colorfield("#F08300", "蜜柑色")
    柳色: Color = colorfield("#A8C97F", "柳色")
    紺色: Color = colorfield("#223A70", "紺色")
    胡粉色: Color = colorfield("#FFFFFC", "胡粉色")
    枯草色: Color = colorfield("#E4DC8A", "枯草色")
    鉛丹色: Color = colorfield("#EC6D51", "鉛丹色")
    青白橡: Color = colorfield("#9BA88D", "青白橡")
    紺青: Color = colorfield("#192F60", "紺青")
    卯の花色: Color = colorfield("#F7FCFE", "卯の花色")
    淡黄: Color = colorfield("#F8E58C", "淡黄")
    黄丹: Color = colorfield("#EE7948", "黄丹")
    柳鼠: Color = colorfield("#C8D5BB", "柳鼠")
    留紺: Color = colorfield("#1C305C", "留紺")
    白磁: Color = colorfield("#F8FBF8", "白磁")
    白茶: Color = colorfield("#DDBB99", "白茶")
    柿色: Color = colorfield("#ED6D3D", "柿色")
    裏葉柳: Color = colorfield("#C1D8AC", "裏葉柳")
    濃藍: Color = colorfield("#0F2350", "濃藍")
    生成り色: Color = colorfield("#FBFAF5", "生成り色")
    赤白橡: Color = colorfield("#D7A98C", "赤白橡")
    黄赤: Color = colorfield("#EC6800", "黄赤")
    山葵色: Color = colorfield("#A8BF93", "山葵色")
    鉄紺: Color = colorfield("#17184B", "鉄紺")
    乳白色: Color = colorfield("#F3F3F3", "乳白色")
    洗柿: Color = colorfield("#F2C9AC", "洗柿")
    人参色: Color = colorfield("#EC6800", "人参色")
    老竹色: Color = colorfield("#769164", "老竹色")
    漆黒: Color = colorfield("#0D0015", "漆黒")
    白練: Color = colorfield("#F3F3F2", "白練")
    鳥の子色: Color = colorfield("#FFF1CF", "鳥の子色")
    橙色: Color = colorfield("#EE7800", "橙色")
    白緑: Color = colorfield("#D6E9CA", "白緑")
    淡藤色: Color = colorfield("#BBC8E6", "淡藤色")
    素色: Color = colorfield("#EAE5E3", "素色")
    蜂蜜色: Color = colorfield("#FDDEA5", "蜂蜜色")
    照柿: Color = colorfield("#EB6238", "照柿")
    淡萌黄: Color = colorfield("#93CA76", "淡萌黄")
    藤色: Color = colorfield("#BBBCDE", "藤色")
    白梅鼠: Color = colorfield("#E5E4E6", "白梅鼠")
    肌色: Color = colorfield("#FCE2C4", "肌色")
    赤橙: Color = colorfield("#EA5506", "赤橙")
    柳染: Color = colorfield("#93B881", "柳染")
    紅掛空色: Color = colorfield("#8491C3", "紅掛空色")
    白鼠: Color = colorfield("#DCDDDD", "白鼠")
    薄卵色: Color = colorfield("#FDE8D0", "薄卵色")
    金赤: Color = colorfield("#EA5506", "金赤")
    薄萌葱: Color = colorfield("#BADCAD", "薄萌葱")
    紅碧: Color = colorfield("#8491C3", "紅碧")
    絹鼠: Color = colorfield("#DDDCD6", "絹鼠")
    雄黄: Color = colorfield("#F9C89B", "雄黄")
    朱色: Color = colorfield("#EB6101", "朱色")
    深川鼠: Color = colorfield("#97A791", "深川鼠")
    紺桔梗: Color = colorfield("#4D5AAF", "紺桔梗")
    灰青: Color = colorfield("#C0C6C9", "灰青")
    洒落柿: Color = colorfield("#F7BD8F", "洒落柿")
    小麦色: Color = colorfield("#E49E61", "小麦色")
    若緑: Color = colorfield("#98D98E", "若緑")
    花色: Color = colorfield("#4D5AAF", "花色")
    銀鼠: Color = colorfield("#AFAFB0", "銀鼠")
    赤香: Color = colorfield("#F6B894", "赤香")
    丹色: Color = colorfield("#E45E32", "丹色")
    浅緑: Color = colorfield("#88CB7F", "浅緑")
    紺藍: Color = colorfield("#4A488E", "紺藍")
    薄鈍: Color = colorfield("#ADADAD", "薄鈍")
    砥粉色: Color = colorfield("#F4DDA5", "砥粉色")
    黄茶: Color = colorfield("#E17B34", "黄茶")
    薄緑: Color = colorfield("#69B076", "薄緑")
    紅桔梗: Color = colorfield("#4D4398", "紅桔梗")
    薄墨色: Color = colorfield("#A3A3A2", "薄墨色")
    肉色: Color = colorfield("#F1BF99", "肉色")
    肉桂色: Color = colorfield("#DD7A56", "肉桂色")
    青鈍: Color = colorfield("#6B7B6E", "青鈍")
    桔梗色: Color = colorfield("#5654A2", "桔梗色")
    錫色: Color = colorfield("#9EA1A3", "錫色")
    人色: Color = colorfield("#F1BF99", "人色")
    赤朽葉色: Color = colorfield("#DB8449", "赤朽葉色")
    青磁鼠: Color = colorfield("#BED2C3", "青磁鼠")
    藤納戸: Color = colorfield("#706CAA", "藤納戸")
    素鼠: Color = colorfield("#9FA0A0", "素鼠")
    丁子色: Color = colorfield("#EFCD9A", "丁子色")
    黄櫨染: Color = colorfield("#D66A35", "黄櫨染")
    薄青: Color = colorfield("#93B69C", "薄青")
    紅掛花色: Color = colorfield("#68699B", "紅掛花色")
    鼠色: Color = colorfield("#949495", "鼠色")
    香色: Color = colorfield("#EFCD9A", "香色")
    蒲公英色: Color = colorfield("#FFD900", "蒲公英色")
    錆青磁: Color = colorfield("#A6C8B2", "錆青磁")
    紫苑色: Color = colorfield("#867BA9", "紫苑色")
    源氏鼠: Color = colorfield("#888084", "源氏鼠")
    薄香: Color = colorfield("#F0CFA0", "薄香")
    黄色: Color = colorfield("#FFD900", "黄色")
    緑青色: Color = colorfield("#47885E", "緑青色")
    白藤色: Color = colorfield("#DBD0E6", "白藤色")
    灰色: Color = colorfield("#7D7D7D", "灰色")
    浅黄: Color = colorfield("#EDD3A1", "浅黄")
    中黄: Color = colorfield("#FFEA00", "中黄")
    千歳緑: Color = colorfield("#316745", "千歳緑")
    藤紫: Color = colorfield("#A59ACA", "藤紫")
    鉛色: Color = colorfield("#7B7C7D", "鉛色")
    枯色: Color = colorfield("#E0C38C", "枯色")
    菜の花色: Color = colorfield("#FFEC47", "菜の花色")
    若竹色: Color = colorfield("#68BE8D", "若竹色")
    菫色: Color = colorfield("#7058A3", "菫色")
    鈍色: Color = colorfield("#727171", "鈍色")
    淡香: Color = colorfield("#F3BF88", "淡香")
    黄檗色: Color = colorfield("#FEF263", "黄檗色")
    緑: Color = colorfield("#3EB370", "緑")
    青紫: Color = colorfield("#674598", "青紫")
    墨: Color = colorfield("#595857", "墨")
    杏色: Color = colorfield("#F7B977", "杏色")
    卵色: Color = colorfield("#FCD575", "卵色")
    常磐色: Color = colorfield("#007B43", "常磐色")
    菖蒲色: Color = colorfield("#674196", "菖蒲色")
    丼鼠: Color = colorfield("#595455", "丼鼠")
    東雲色: Color = colorfield("#F19072", "東雲色")
    花葉色: Color = colorfield("#FBD26B", "花葉色")
    千草鼠: Color = colorfield("#BED3CA", "千草鼠")
    竜胆色: Color = colorfield("#9079AD", "竜胆色")
    消炭色: Color = colorfield("#524E4D", "消炭色")
    曙色: Color = colorfield("#F19072", "曙色")
    刈安色: Color = colorfield("#F5E56B", "刈安色")
    千草色: Color = colorfield("#92B5A9", "千草色")
    江戸紫: Color = colorfield("#745399", "江戸紫")
    藍墨茶: Color = colorfield("#474A4D", "藍墨茶")
    珊瑚朱色: Color = colorfield("#EE836F", "珊瑚朱色")
    玉蜀黍色: Color = colorfield("#EEC362", "玉蜀黍色")
    青磁色: Color = colorfield("#7EBEA5", "青磁色")
    本紫: Color = colorfield("#65318E", "本紫")
    羊羹色: Color = colorfield("#383C3C", "羊羹色")
    深支子: Color = colorfield("#EB9B6F", "深支子")
    金糸雀色: Color = colorfield("#EBD842", "金糸雀色")
    青竹色: Color = colorfield("#7EBEAB", "青竹色")
    葡萄色: Color = colorfield("#522F60", "葡萄色")
    蝋色: Color = colorfield("#2B2B2B", "蝋色")
    纁: Color = colorfield("#E0815E", "纁")
    黄支子色: Color = colorfield("#FFDB4F", "黄支子色")
    常磐緑: Color = colorfield("#028760", "常磐緑")
    深紫: Color = colorfield("#493759", "深紫")
    黒: Color = colorfield("#2B2B2B", "黒")
    浅緋: Color = colorfield("#DF7163", "浅緋")
    支子色: Color = colorfield("#FBCA4D", "支子色")
    木賊色: Color = colorfield("#3B7960", "木賊色")
    紫黒: Color = colorfield("#2E2930", "紫黒")
    烏羽色: Color = colorfield("#180614", "烏羽色")
    真赭: Color = colorfield("#D57C6B", "真赭")
    向日葵色: Color = colorfield("#FCC800", "向日葵色")
    天鵞絨: Color = colorfield("#2F5D50", "天鵞絨")
    紫: Color = colorfield("#884898", "紫")
    鉄黒: Color = colorfield("#281A14", "鉄黒")
    洗朱: Color = colorfield("#D0826C", "洗朱")
    山吹色: Color = colorfield("#F8B500", "山吹色")
    虫襖: Color = colorfield("#3A5B52", "虫襖")
    薄葡萄: Color = colorfield("#C0A2C7", "薄葡萄")
    濡羽色: Color = colorfield("#000B00", "濡羽色")
    遠州茶: Color = colorfield("#CA8269", "遠州茶")
    鬱金色: Color = colorfield("#FABF14", "鬱金色")
    革色: Color = colorfield("#475950", "革色")
    紫紺: Color = colorfield("#460E44", "紫紺")
    黒檀: Color = colorfield("#250D00", "黒檀")
    紅樺色: Color = colorfield("#BB5548", "紅樺色")
    藤黄: Color = colorfield("#F7C114", "藤黄")
    深緑: Color = colorfield("#00552E", "深緑")
    暗紅色: Color = colorfield("#74325C", "暗紅色")
    憲法黒茶: Color = colorfield("#241A08", "憲法黒茶")
    赭: Color = colorfield("#AB6953", "赭")
    金色: Color = colorfield("#E6B422", "金色")
    鉄色: Color = colorfield("#005243", "鉄色")
    桑の実色: Color = colorfield("#55295B", "桑の実色")
    暗黒色: Color = colorfield("#16160E", "暗黒色")
    さくらいろ: Color = colorfield("#FEF4F4", "さくらいろ")
    あずきいろ: Color = colorfield("#96514D", "あずきいろ")
    こがね: Color = colorfield("#E6B422", "こがね")
    もえぎいろ: Color = colorfield("#006E54", "もえぎいろ")
    こだいむらさき: Color = colorfield("#895B8A", "こだいむらさき")
    うすざくら: Color = colorfield("#FDEFF2", "うすざくら")
    からちゃ: Color = colorfield("#8D6449", "からちゃ")
    はじぞめ: Color = colorfield("#D9A62E", "はじぞめ")
    はなろくしょう: Color = colorfield("#00A381", "はなろくしょう")
    なすこん: Color = colorfield("#824880", "なすこん")
    さくらねず: Color = colorfield("#E9DFE5", "さくらねず")
    あめいろ: Color = colorfield("#DEB068", "あめいろ")
    きくちばいろ: Color = colorfield("#D3A243", "きくちばいろ")
    ひすいいろ: Color = colorfield("#38B48B", "ひすいいろ")
    ふたあい: Color = colorfield("#915C8B", "ふたあい")
    ときねず: Color = colorfield("#E4D2D8", "ときねず")
    らくだいろ: Color = colorfield("#BF794E", "らくだいろ")
    やまぶきちゃ: Color = colorfield("#C89932", "やまぶきちゃ")
    あおみどり: Color = colorfield("#00A497", "あおみどり")
    きょうむらさき: Color = colorfield("#9D5B8B", "きょうむらさき")
    にじいろ: Color = colorfield("#F6BFBC", "にじいろ")
    つちいろ: Color = colorfield("#BC763C", "つちいろ")
    からしいろ: Color = colorfield("#D0AF4C", "からしいろ")
    みずあさぎ: Color = colorfield("#80ABA9", "みずあさぎ")
    えびぞめ: Color = colorfield("#7A4171", "えびぞめ")
    さんごいろ: Color = colorfield("#F5B1AA", "さんごいろ")
    きがらちゃ: Color = colorfield("#B98C46", "きがらちゃ")
    まめがらちゃ: Color = colorfield("#8B968D", "まめがらちゃ")
    さびあさぎ: Color = colorfield("#5C9291", "さびあさぎ")
    わかむらさき: Color = colorfield("#BC64A4", "わかむらさき")
    いっこんぞめ: Color = colorfield("#F5B199", "いっこんぞめ")
    くわぞめ: Color = colorfield("#B79B5B", "くわぞめ")
    きくじん: Color = colorfield("#6E7955", "きくじん")
    せいへき: Color = colorfield("#478384", "せいへき")
    べにむらさき: Color = colorfield("#B44C97", "べにむらさき")
    ししいろ: Color = colorfield("#EFAB93", "ししいろ")
    はじいろ: Color = colorfield("#B77B57", "はじいろ")
    やまばといろ: Color = colorfield("#767C6B", "やまばといろ")
    おめしちゃ: Color = colorfield("#43676B", "おめしちゃ")
    うめむらさき: Color = colorfield("#AA4C8F", "うめむらさき")
    こうばいいろ: Color = colorfield("#F2A0A1", "こうばいいろ")
    きつるばみ: Color = colorfield("#B68D4C", "きつるばみ")
    りきゅうねずみ: Color = colorfield("#888E7E", "りきゅうねずみ")
    みなとねずみ: Color = colorfield("#80989B", "みなとねずみ")
    あやめいろ: Color = colorfield("#CC7EB1", "あやめいろ")
    うすべに: Color = colorfield("#F0908D", "うすべに")
    ちょうじぞめ: Color = colorfield("#AD7D4C", "ちょうじぞめ")
    みるちゃ: Color = colorfield("#5A544B", "みるちゃ")
    こうらいなんど: Color = colorfield("#2C4F54", "こうらいなんど")
    べにふじいろ: Color = colorfield("#CCA6BF", "べにふじいろ")
    じんざもみ: Color = colorfield("#EE827C", "じんざもみ")
    こうぞめ: Color = colorfield("#AD7D4C", "こうぞめ")
    あいみるちゃ: Color = colorfield("#56564B", "あいみるちゃ")
    ももしおちゃ: Color = colorfield("#1F3134", "ももしおちゃ")
    あさむらさき: Color = colorfield("#C4A3BF", "あさむらさき")
    ももいろ: Color = colorfield("#F09199", "ももいろ")
    びわちゃ: Color = colorfield("#AE7C4F", "びわちゃ")
    あいこびちゃ: Color = colorfield("#555647", "あいこびちゃ")
    さびねず: Color = colorfield("#47585C", "さびねず")
    むらさきすいしょう: Color = colorfield("#E7E7EB", "むらさきすいしょう")
    ときいろ: Color = colorfield("#F4B3C2", "ときいろ")
    しかんちゃ: Color = colorfield("#AD7E4E", "しかんちゃ")
    せんさいちゃ: Color = colorfield("#494A41", "せんさいちゃ")
    さびてつおなんど: Color = colorfield("#485859", "さびてつおなんど")
    うすうめねず: Color = colorfield("#DCD6D9", "うすうめねず")
    なでしこいろ: Color = colorfield("#EEBBCB", "なでしこいろ")
    こがれこう: Color = colorfield("#AE7C58", "こがれこう")
    いわいちゃ: Color = colorfield("#6B6F59", "いわいちゃ")
    あいねず: Color = colorfield("#6C848D", "あいねず")
    あかつきねず: Color = colorfield("#D3CFD9", "あかつきねず")
    はいうめ: Color = colorfield("#E8D3C7", "はいうめ")
    くるみいろ: Color = colorfield("#A86F4C", "くるみいろ")
    せんさいちゃ: Color = colorfield("#474B42", "せんさいちゃ")
    さびおなんど: Color = colorfield("#53727D", "さびおなんど")
    ぼたんねず: Color = colorfield("#D3CCD6", "ぼたんねず")
    はいざくら: Color = colorfield("#E8D3D1", "はいざくら")
    しぶかみいろ: Color = colorfield("#946243", "しぶかみいろ")
    くろみどり: Color = colorfield("#333631", "くろみどり")
    ますはないろ: Color = colorfield("#5B7E91", "ますはないろ")
    かすみいろ: Color = colorfield("#C8C2C6", "かすみいろ")
    あわべにふじ: Color = colorfield("#E6CDE3", "あわべにふじ")
    くちばいろ: Color = colorfield("#917347", "くちばいろ")
    やなぎすすたけ: Color = colorfield("#5B6356", "やなぎすすたけ")
    のしめはないろ: Color = colorfield("#426579", "のしめはないろ")
    ふじねず: Color = colorfield("#A6A5C4", "ふじねず")
    せきちくいろ: Color = colorfield("#E5ABBE", "せきちくいろ")
    くわちゃ: Color = colorfield("#956F29", "くわちゃ")
    かばちゃいろ: Color = colorfield("#726250", "かばちゃいろ")
    おめしおなんど: Color = colorfield("#4C6473", "おめしおなんど")
    はしたいろ: Color = colorfield("#A69ABD", "はしたいろ")
    うすこうばい: Color = colorfield("#E597B2", "うすこうばい")
    ろこうちゃ: Color = colorfield("#8C7042", "ろこうちゃ")
    うつぶしいろ: Color = colorfield("#9D896C", "うつぶしいろ")
    てつおなんど: Color = colorfield("#455765", "てつおなんど")
    うすいろ: Color = colorfield("#A89DAC", "うすいろ")
    ももはないろ: Color = colorfield("#E198B4", "ももはないろ")
    こくぼうしょく: Color = colorfield("#7B6C3E", "こくぼうしょく")
    なまかべいろ: Color = colorfield("#94846A", "なまかべいろ")
    こんねず: Color = colorfield("#44617B", "こんねず")
    うすねず: Color = colorfield("#9790A4", "うすねず")
    みずがき: Color = colorfield("#E4AB9B", "みずがき")
    きゃらいろ: Color = colorfield("#D8A373", "きゃらいろ")
    ひごすすたけ: Color = colorfield("#897858", "ひごすすたけ")
    あいてつ: Color = colorfield("#393F4C", "あいてつ")
    はとばねずみ: Color = colorfield("#9E8B8E", "はとばねずみ")
    ときがらちゃ: Color = colorfield("#E09E87", "ときがらちゃ")
    えどちゃ: Color = colorfield("#CD8C5C", "えどちゃ")
    こびちゃ: Color = colorfield("#716246", "こびちゃ")
    あおかち: Color = colorfield("#393E4F", "あおかち")
    はとばいろ: Color = colorfield("#95859C", "はとばいろ")
    あらぞめ: Color = colorfield("#D69090", "あらぞめ")
    かばいろ: Color = colorfield("#CD5E3C", "かばいろ")
    しろつるばみ: Color = colorfield("#CBB994", "しろつるばみ")
    かちかえし: Color = colorfield("#203744", "かちかえし")
    ききょうねず: Color = colorfield("#95949A", "ききょうねず")
    うすがき: Color = colorfield("#D4ACAD", "うすがき")
    べにうこん: Color = colorfield("#CB8347", "べにうこん")
    あまいろ: Color = colorfield("#D6C6AF", "あまいろ")
    かちいろ: Color = colorfield("#4D4C61", "かちいろ")
    むらさきねず: Color = colorfield("#71686C", "むらさきねず")
    ちょうしゅんいろ: Color = colorfield("#C97586", "ちょうしゅんいろ")
    かわらけいろ: Color = colorfield("#C37854", "かわらけいろ")
    はしばみいろ: Color = colorfield("#BFA46F", "はしばみいろ")
    げっぱく: Color = colorfield("#EAF4FC", "げっぱく")
    ぶどうねずみ: Color = colorfield("#705B67", "ぶどうねずみ")
    うめねず: Color = colorfield("#C099A0", "うめねず")
    きつねいろ: Color = colorfield("#C38743", "きつねいろ")
    あくいろ: Color = colorfield("#9E9478", "あくいろ")
    しろすみれいろ: Color = colorfield("#EAEDF7", "しろすみれいろ")
    こきいろ: Color = colorfield("#634950", "こきいろ")
    ときあさぎ: Color = colorfield("#B88884", "ときあさぎ")
    おうどいろ: Color = colorfield("#C39143", "おうどいろ")
    りきゅうちゃ: Color = colorfield("#A59564", "りきゅうちゃ")
    しらはないろ: Color = colorfield("#E8ECEF", "しらはないろ")
    むらさきとび: Color = colorfield("#5F414B", "むらさきとび")
    うめぞめ: Color = colorfield("#B48A76", "うめぞめ")
    こはくいろ: Color = colorfield("#BF783A", "こはくいろ")
    うぐいすちゃ: Color = colorfield("#715C1F", "うぐいすちゃ")
    あいじろ: Color = colorfield("#EBF6F7", "あいじろ")
    こいねず: Color = colorfield("#4F455C", "こいねず")
    すおうこう: Color = colorfield("#A86965", "すおうこう")
    あかちゃ: Color = colorfield("#BB5535", "あかちゃ")
    もくらんじき: Color = colorfield("#C7B370", "もくらんじき")
    しらあい: Color = colorfield("#C1E4E9", "しらあい")
    ふじすすたけ: Color = colorfield("#5A5359", "ふじすすたけ")
    あさすおう: Color = colorfield("#A25768", "あさすおう")
    たいしゃ: Color = colorfield("#BB5520", "たいしゃ")
    すないろ: Color = colorfield("#DCD3B2", "すないろ")
    みずいろ: Color = colorfield("#BCE2E8", "みずいろ")
    けしむらさき: Color = colorfield("#594255", "けしむらさき")
    まそお: Color = colorfield("#EC6D71", "まそお")
    れんがいろ: Color = colorfield("#B55233", "れんがいろ")
    あぶらいろ: Color = colorfield("#A19361", "あぶらいろ")
    かめのぞき: Color = colorfield("#A2D7DD", "かめのぞき")
    べにけしねずみ: Color = colorfield("#524748", "べにけしねずみ")
    あかむらさき: Color = colorfield("#EB6EA5", "あかむらさき")
    すずめちゃ: Color = colorfield("#AA4F37", "すずめちゃ")
    りきゅういろ: Color = colorfield("#8F8667", "りきゅういろ")
    ひそくいろ: Color = colorfield("#ABCED8", "ひそくいろ")
    にせむらさき: Color = colorfield("#513743", "にせむらさき")
    つつじいろ: Color = colorfield("#E95295", "つつじいろ")
    だんじゅうろうちゃ: Color = colorfield("#9F563A", "だんじゅうろうちゃ")
    ばいこうちゃ: Color = colorfield("#887938", "ばいこうちゃ")
    そらいろ: Color = colorfield("#A0D8EF", "そらいろ")
    はいきみどり: Color = colorfield("#E6EAE3", "はいきみどり")
    ぼたんいろ: Color = colorfield("#E7609E", "ぼたんいろ")
    かきしぶいろ: Color = colorfield("#9F563A", "かきしぶいろ")
    りかんちゃ: Color = colorfield("#6A5D21", "りかんちゃ")
    わすれなぐさいろ: Color = colorfield("#89C3EB", "わすれなぐさいろ")
    そばきりいろ: Color = colorfield("#D4DCD6", "そばきりいろ")
    いまよういろ: Color = colorfield("#D0576B", "いまよういろ")
    べにとび: Color = colorfield("#9A493F", "べにとび")
    きみるちゃ: Color = colorfield("#918754", "きみるちゃ")
    あおふじいろ: Color = colorfield("#84A2D4", "あおふじいろ")
    うすくもねず: Color = colorfield("#D4DCDA", "うすくもねず")
    なかべに: Color = colorfield("#C85179", "なかべに")
    はいちゃ: Color = colorfield("#98623C", "はいちゃ")
    なたねゆいろ: Color = colorfield("#A69425", "なたねゆいろ")
    びゃくぐん: Color = colorfield("#83CCD2", "びゃくぐん")
    かれのいろ: Color = colorfield("#D3CBC6", "かれのいろ")
    ばらいろ: Color = colorfield("#E9546B", "ばらいろ")
    ちゃいろ: Color = colorfield("#965042", "ちゃいろ")
    あおくちば: Color = colorfield("#ADA250", "あおくちば")
    あさはなだ: Color = colorfield("#84B9CB", "あさはなだ")
    うるみいろ: Color = colorfield("#C8C2BE", "うるみいろ")
    からくれない: Color = colorfield("#E95464", "からくれない")
    ひわだいろ: Color = colorfield("#965036", "ひわだいろ")
    ねぎしいろ: Color = colorfield("#938B4B", "ねぎしいろ")
    うすはないろ: Color = colorfield("#698AAB", "うすはないろ")
    りきゅうしろちゃ: Color = colorfield("#B3ADA0", "りきゅうしろちゃ")
    ぎんしゅ: Color = colorfield("#C85554", "ぎんしゅ")
    とびいろ: Color = colorfield("#95483F", "とびいろ")
    ひわちゃ: Color = colorfield("#8C8861", "ひわちゃ")
    なんどいろ: Color = colorfield("#008899", "なんどいろ")
    ちゃねずみ: Color = colorfield("#A99E93", "ちゃねずみ")
    あかべに: Color = colorfield("#C53D43", "あかべに")
    かきちゃ: Color = colorfield("#954E2A", "かきちゃ")
    やなぎちゃ: Color = colorfield("#A1A46D", "やなぎちゃ")
    あさぎいろ: Color = colorfield("#00A3AF", "あさぎいろ")
    くるみぞめ: Color = colorfield("#A58F86", "くるみぞめ")
    べにひ: Color = colorfield("#E83929", "べにひ")
    べんがらいろ: Color = colorfield("#8F2E14", "べんがらいろ")
    みるいろ: Color = colorfield("#726D40", "みるいろ")
    はなあさぎ: Color = colorfield("#2A83A2", "はなあさぎ")
    えどねず: Color = colorfield("#928178", "えどねず")
    あか: Color = colorfield("#E60033", "あか")
    あかさびいろ: Color = colorfield("#8A3319", "あかさびいろ")
    うぐいすいろ: Color = colorfield("#928C36", "うぐいすいろ")
    しんばしいろ: Color = colorfield("#59B9C6", "しんばしいろ")
    すすいろ: Color = colorfield("#887F7A", "すすいろ")
    しょうじょうひ: Color = colorfield("#E2041B", "しょうじょうひ")
    かっしょく: Color = colorfield("#8A3B00", "かっしょく")
    りょくおうしょく: Color = colorfield("#DCCB18", "りょくおうしょく")
    あまいろ: Color = colorfield("#2CA9E1", "あまいろ")
    ちょうじちゃ: Color = colorfield("#B4866B", "ちょうじちゃ")
    くれない: Color = colorfield("#D7003A", "くれない")
    くりうめ: Color = colorfield("#852E19", "くりうめ")
    ひわいろ: Color = colorfield("#D7CF3A", "ひわいろ")
    つゆくさいろ: Color = colorfield("#38A1DB", "つゆくさいろ")
    ふしぞめ: Color = colorfield("#B28C6E", "ふしぞめ")
    こきひ: Color = colorfield("#C9171E", "こきひ")
    べにひはだ: Color = colorfield("#7B4741", "べにひはだ")
    まっちゃいろ: Color = colorfield("#C5C56A", "まっちゃいろ")
    あお: Color = colorfield("#0095D9", "あお")
    そうでんからちゃ: Color = colorfield("#A16D5D", "そうでんからちゃ")
    ひいろ: Color = colorfield("#D3381C", "ひいろ")
    えびちゃ: Color = colorfield("#773C30", "えびちゃ")
    わかくさいろ: Color = colorfield("#C3D825", "わかくさいろ")
    うすあい: Color = colorfield("#0094C8", "うすあい")
    とのちゃ: Color = colorfield("#9F6F55", "とのちゃ")
    あかに: Color = colorfield("#CE5242", "あかに")
    からちゃ: Color = colorfield("#783C1D", "からちゃ")
    きみどり: Color = colorfield("#B8D200", "きみどり")
    はなだいろ: Color = colorfield("#2792C3", "はなだいろ")
    せんちゃいろ: Color = colorfield("#8C6450", "せんちゃいろ")
    べにあか: Color = colorfield("#D9333F", "べにあか")
    くりいろ: Color = colorfield("#762F07", "くりいろ")
    わかめいろ: Color = colorfield("#E0EBAF", "わかめいろ")
    こんぺき: Color = colorfield("#007BBB", "こんぺき")
    ぎんすすだけ: Color = colorfield("#856859", "ぎんすすだけ")
    えんじ: Color = colorfield("#B94047", "えんじ")
    しゃくどういろ: Color = colorfield("#752100", "しゃくどういろ")
    わかないろ: Color = colorfield("#D8E698", "わかないろ")
    うすぐんじょう: Color = colorfield("#5383C3", "うすぐんじょう")
    きがらちゃ: Color = colorfield("#765C47", "きがらちゃ")
    あけ: Color = colorfield("#BA2636", "あけ")
    さびいろ: Color = colorfield("#6C3524", "さびいろ")
    わかなえいろ: Color = colorfield("#C7DC68", "わかなえいろ")
    うすはなざくら: Color = colorfield("#5A79BA", "うすはなざくら")
    すすたけいろ: Color = colorfield("#6F514C", "すすたけいろ")
    あかねいろ: Color = colorfield("#B7282E", "あかねいろ")
    せっかっしょく: Color = colorfield("#683F36", "せっかっしょく")
    あおに: Color = colorfield("#99AB4E", "あおに")
    ぐんじょういろ: Color = colorfield("#4C6CB3", "ぐんじょういろ")
    こげちゃ: Color = colorfield("#6F4B3E", "こげちゃ")
    べにえびちゃ: Color = colorfield("#A73836", "べにえびちゃ")
    ちゃかっしょく: Color = colorfield("#664032", "ちゃかっしょく")
    くさいろ: Color = colorfield("#7B8D42", "くさいろ")
    かきつばたいろ: Color = colorfield("#3E62AD", "かきつばたいろ")
    くろつるばみ: Color = colorfield("#544A47", "くろつるばみ")
    すおう: Color = colorfield("#9E3D3F", "すおう")
    くりかわちゃ: Color = colorfield("#6D3C32", "くりかわちゃ")
    こけいろ: Color = colorfield("#69821B", "こけいろ")
    るりいろ: Color = colorfield("#1E50A2", "るりいろ")
    けんぽういろ: Color = colorfield("#543F32", "けんぽういろ")
    しんく: Color = colorfield("#A22041", "しんく")
    くろちゃ: Color = colorfield("#583822", "くろちゃ")
    もえぎ: Color = colorfield("#AACF53", "もえぎ")
    うすはなだ: Color = colorfield("#507EA4", "うすはなだ")
    くりいろ: Color = colorfield("#554738", "くりいろ")
    こいくれない: Color = colorfield("#A22041", "こいくれない")
    えびちゃ: Color = colorfield("#6C2C2F", "えびちゃ")
    なえいろ: Color = colorfield("#B0CA71", "なえいろ")
    るりこん: Color = colorfield("#19448E", "るりこん")
    びんろうじぞめ: Color = colorfield("#433D3C", "びんろうじぞめ")
    ぞうげいろ: Color = colorfield("#F8F4E6", "ぞうげいろ")
    えびいろ: Color = colorfield("#640125", "えびいろ")
    わかばいろ: Color = colorfield("#B9D08B", "わかばいろ")
    こんるり: Color = colorfield("#164A84", "こんるり")
    くろとび: Color = colorfield("#432F2F", "くろとび")
    ねりいろ: Color = colorfield("#EDE4CD", "ねりいろ")
    かんぞういろ: Color = colorfield("#F8B862", "かんぞういろ")
    まつばいろ: Color = colorfield("#839B5C", "まつばいろ")
    あいいろ: Color = colorfield("#165E83", "あいいろ")
    あかすみ: Color = colorfield("#3F312B", "あかすみ")
    かいはくしょく: Color = colorfield("#E9E4D4", "かいはくしょく")
    こうじいろ: Color = colorfield("#F6AD49", "こうじいろ")
    なつむしいろ: Color = colorfield("#CEE4AE", "なつむしいろ")
    せいらん: Color = colorfield("#274A78", "せいらん")
    くろべに: Color = colorfield("#302833", "くろべに")
    むしぐりいろ: Color = colorfield("#EBE1A9", "むしぐりいろ")
    きんちゃ: Color = colorfield("#F39800", "きんちゃ")
    ひわもえぎ: Color = colorfield("#82AE46", "ひわもえぎ")
    こきはなだ: Color = colorfield("#2A4073", "こきはなだ")
    しろ: Color = colorfield("#FFFFFF", "しろ")
    おみなえし: Color = colorfield("#F2F2B0", "おみなえし")
    みかんいろ: Color = colorfield("#F08300", "みかんいろ")
    やなぎいろ: Color = colorfield("#A8C97F", "やなぎいろ")
    こんいろ: Color = colorfield("#223A70", "こんいろ")
    ごふんいろ: Color = colorfield("#FFFFFC", "ごふんいろ")
    かれくさいろ: Color = colorfield("#E4DC8A", "かれくさいろ")
    えんたんいろ: Color = colorfield("#EC6D51", "えんたんいろ")
    あおしろつるばみ: Color = colorfield("#9BA88D", "あおしろつるばみ")
    こんじょう: Color = colorfield("#192F60", "こんじょう")
    うのはないろ: Color = colorfield("#F7FCFE", "うのはないろ")
    たんこう: Color = colorfield("#F8E58C", "たんこう")
    おうに: Color = colorfield("#EE7948", "おうに")
    やなぎねず: Color = colorfield("#C8D5BB", "やなぎねず")
    とめこん: Color = colorfield("#1C305C", "とめこん")
    はくじ: Color = colorfield("#F8FBF8", "はくじ")
    しらちゃ: Color = colorfield("#DDBB99", "しらちゃ")
    かきいろ: Color = colorfield("#ED6D3D", "かきいろ")
    うらはやなぎ: Color = colorfield("#C1D8AC", "うらはやなぎ")
    こいあい: Color = colorfield("#0F2350", "こいあい")
    きなりいろ: Color = colorfield("#FBFAF5", "きなりいろ")
    あかしろつるばみ: Color = colorfield("#D7A98C", "あかしろつるばみ")
    きあか: Color = colorfield("#EC6800", "きあか")
    わさびいろ: Color = colorfield("#A8BF93", "わさびいろ")
    てつこん: Color = colorfield("#17184B", "てつこん")
    にゅうはくしょく: Color = colorfield("#F3F3F3", "にゅうはくしょく")
    あらいがき: Color = colorfield("#F2C9AC", "あらいがき")
    にんじんいろ: Color = colorfield("#EC6800", "にんじんいろ")
    おいたけいろ: Color = colorfield("#769164", "おいたけいろ")
    しっこく: Color = colorfield("#0D0015", "しっこく")
    しろねり: Color = colorfield("#F3F3F2", "しろねり")
    とりのこいろ: Color = colorfield("#FFF1CF", "とりのこいろ")
    だいだいいろ: Color = colorfield("#EE7800", "だいだいいろ")
    びゃくろく: Color = colorfield("#D6E9CA", "びゃくろく")
    あわふじいろ: Color = colorfield("#BBC8E6", "あわふじいろ")
    そしょく: Color = colorfield("#EAE5E3", "そしょく")
    はちみついろ: Color = colorfield("#FDDEA5", "はちみついろ")
    てりがき: Color = colorfield("#EB6238", "てりがき")
    うすもえぎ: Color = colorfield("#93CA76", "うすもえぎ")
    ふじいろ: Color = colorfield("#BBBCDE", "ふじいろ")
    しらうめねず: Color = colorfield("#E5E4E6", "しらうめねず")
    はだいろ: Color = colorfield("#FCE2C4", "はだいろ")
    あかだいだい: Color = colorfield("#EA5506", "あかだいだい")
    やなぎぞめ: Color = colorfield("#93B881", "やなぎぞめ")
    べにかけそらいろ: Color = colorfield("#8491C3", "べにかけそらいろ")
    しろねず: Color = colorfield("#DCDDDD", "しろねず")
    うすたまごいろ: Color = colorfield("#FDE8D0", "うすたまごいろ")
    きんあか: Color = colorfield("#EA5506", "きんあか")
    うすもえぎ: Color = colorfield("#BADCAD", "うすもえぎ")
    べにみどり: Color = colorfield("#8491C3", "べにみどり")
    きぬねず: Color = colorfield("#DDDCD6", "きぬねず")
    ゆうおう: Color = colorfield("#F9C89B", "ゆうおう")
    しゅいろ: Color = colorfield("#EB6101", "しゅいろ")
    ふかがわねずみ: Color = colorfield("#97A791", "ふかがわねずみ")
    こんききょう: Color = colorfield("#4D5AAF", "こんききょう")
    はいあお: Color = colorfield("#C0C6C9", "はいあお")
    しゃれがき: Color = colorfield("#F7BD8F", "しゃれがき")
    こむぎいろ: Color = colorfield("#E49E61", "こむぎいろ")
    わかみどり: Color = colorfield("#98D98E", "わかみどり")
    はないろ: Color = colorfield("#4D5AAF", "はないろ")
    ぎんねず: Color = colorfield("#AFAFB0", "ぎんねず")
    あかこう: Color = colorfield("#F6B894", "あかこう")
    にいろ: Color = colorfield("#E45E32", "にいろ")
    あさみどり: Color = colorfield("#88CB7F", "あさみどり")
    こんあい: Color = colorfield("#4A488E", "こんあい")
    うすにび: Color = colorfield("#ADADAD", "うすにび")
    とのこいろ: Color = colorfield("#F4DDA5", "とのこいろ")
    きちゃ: Color = colorfield("#E17B34", "きちゃ")
    うすみどり: Color = colorfield("#69B076", "うすみどり")
    べにききょう: Color = colorfield("#4D4398", "べにききょう")
    うすずみいろ: Color = colorfield("#A3A3A2", "うすずみいろ")
    にくいろ: Color = colorfield("#F1BF99", "にくいろ")
    にっけいいろ: Color = colorfield("#DD7A56", "にっけいいろ")
    あおにび: Color = colorfield("#6B7B6E", "あおにび")
    ききょういろ: Color = colorfield("#5654A2", "ききょういろ")
    すずいろ: Color = colorfield("#9EA1A3", "すずいろ")
    ひといろ: Color = colorfield("#F1BF99", "ひといろ")
    あかくちばいろ: Color = colorfield("#DB8449", "あかくちばいろ")
    せいじねず: Color = colorfield("#BED2C3", "せいじねず")
    ふじなんど: Color = colorfield("#706CAA", "ふじなんど")
    すねずみ: Color = colorfield("#9FA0A0", "すねずみ")
    ちょうじいろ: Color = colorfield("#EFCD9A", "ちょうじいろ")
    こうろぜん: Color = colorfield("#D66A35", "こうろぜん")
    うすあお: Color = colorfield("#93B69C", "うすあお")
    べにかけはないろ: Color = colorfield("#68699B", "べにかけはないろ")
    ねずみいろ: Color = colorfield("#949495", "ねずみいろ")
    こういろ: Color = colorfield("#EFCD9A", "こういろ")
    たんぽぽいろ: Color = colorfield("#FFD900", "たんぽぽいろ")
    さびせいじ: Color = colorfield("#A6C8B2", "さびせいじ")
    しおんいろ: Color = colorfield("#867BA9", "しおんいろ")
    げんじねず: Color = colorfield("#888084", "げんじねず")
    うすこう: Color = colorfield("#F0CFA0", "うすこう")
    きいろ: Color = colorfield("#FFD900", "きいろ")
    ろくしょういろ: Color = colorfield("#47885E", "ろくしょういろ")
    しらふじいろ: Color = colorfield("#DBD0E6", "しらふじいろ")
    はいいろ: Color = colorfield("#7D7D7D", "はいいろ")
    うすき: Color = colorfield("#EDD3A1", "うすき")
    ちゅうき: Color = colorfield("#FFEA00", "ちゅうき")
    ちとせみどり: Color = colorfield("#316745", "ちとせみどり")
    ふじむらさき: Color = colorfield("#A59ACA", "ふじむらさき")
    なまりいろ: Color = colorfield("#7B7C7D", "なまりいろ")
    かれいろ: Color = colorfield("#E0C38C", "かれいろ")
    なのはないろ: Color = colorfield("#FFEC47", "なのはないろ")
    わかたけいろ: Color = colorfield("#68BE8D", "わかたけいろ")
    すみれいろ: Color = colorfield("#7058A3", "すみれいろ")
    にびいろ: Color = colorfield("#727171", "にびいろ")
    うすこう: Color = colorfield("#F3BF88", "うすこう")
    きはだいろ: Color = colorfield("#FEF263", "きはだいろ")
    みどり: Color = colorfield("#3EB370", "みどり")
    あおむらさき: Color = colorfield("#674598", "あおむらさき")
    すみ: Color = colorfield("#595857", "すみ")
    あんずいろ: Color = colorfield("#F7B977", "あんずいろ")
    たまごいろ: Color = colorfield("#FCD575", "たまごいろ")
    ときわいろ: Color = colorfield("#007B43", "ときわいろ")
    しょうぶいろ: Color = colorfield("#674196", "しょうぶいろ")
    どぶねずみ: Color = colorfield("#595455", "どぶねずみ")
    しののめいろ: Color = colorfield("#F19072", "しののめいろ")
    はなばいろ: Color = colorfield("#FBD26B", "はなばいろ")
    ちぐさねず: Color = colorfield("#BED3CA", "ちぐさねず")
    りんどういろ: Color = colorfield("#9079AD", "りんどういろ")
    けしずみいろ: Color = colorfield("#524E4D", "けしずみいろ")
    あけぼのいろ: Color = colorfield("#F19072", "あけぼのいろ")
    かりやすいろ: Color = colorfield("#F5E56B", "かりやすいろ")
    ちぐさいろ: Color = colorfield("#92B5A9", "ちぐさいろ")
    えどむらさき: Color = colorfield("#745399", "えどむらさき")
    あいすみちゃ: Color = colorfield("#474A4D", "あいすみちゃ")
    さんごしゅいろ: Color = colorfield("#EE836F", "さんごしゅいろ")
    とうもろこしいろ: Color = colorfield("#EEC362", "とうもろこしいろ")
    せいじいろ: Color = colorfield("#7EBEA5", "せいじいろ")
    ほんむらさき: Color = colorfield("#65318E", "ほんむらさき")
    ようかんいろ: Color = colorfield("#383C3C", "ようかんいろ")
    こきくちなし: Color = colorfield("#EB9B6F", "こきくちなし")
    かなりあいろ: Color = colorfield("#EBD842", "かなりあいろ")
    あおたけいろ: Color = colorfield("#7EBEAB", "あおたけいろ")
    ぶどういろ: Color = colorfield("#522F60", "ぶどういろ")
    ろういろ: Color = colorfield("#2B2B2B", "ろういろ")
    そひ: Color = colorfield("#E0815E", "そひ")
    きくちなしいろ: Color = colorfield("#FFDB4F", "きくちなしいろ")
    ときわみどり: Color = colorfield("#028760", "ときわみどり")
    ふかむらさき: Color = colorfield("#493759", "ふかむらさき")
    くろ: Color = colorfield("#2B2B2B", "くろ")
    うすきひ: Color = colorfield("#DF7163", "うすきひ")
    くちなしいろ: Color = colorfield("#FBCA4D", "くちなしいろ")
    とくさいろ: Color = colorfield("#3B7960", "とくさいろ")
    しこく: Color = colorfield("#2E2930", "しこく")
    からすばいろ: Color = colorfield("#180614", "からすばいろ")
    まそほ: Color = colorfield("#D57C6B", "まそほ")
    ひまわりいろ: Color = colorfield("#FCC800", "ひまわりいろ")
    びろうど: Color = colorfield("#2F5D50", "びろうど")
    むらさき: Color = colorfield("#884898", "むらさき")
    てつぐろ: Color = colorfield("#281A14", "てつぐろ")
    あらいしゅ: Color = colorfield("#D0826C", "あらいしゅ")
    やまぶきいろ: Color = colorfield("#F8B500", "やまぶきいろ")
    むしあお: Color = colorfield("#3A5B52", "むしあお")
    うすぶどう: Color = colorfield("#C0A2C7", "うすぶどう")
    ぬればいろ: Color = colorfield("#000B00", "ぬればいろ")
    えんしゅうちゃ: Color = colorfield("#CA8269", "えんしゅうちゃ")
    うこんいろ: Color = colorfield("#FABF14", "うこんいろ")
    かわいろ: Color = colorfield("#475950", "かわいろ")
    しこん: Color = colorfield("#460E44", "しこん")
    こくたん: Color = colorfield("#250D00", "こくたん")
    べにかばいろ: Color = colorfield("#BB5548", "べにかばいろ")
    とうおう: Color = colorfield("#F7C114", "とうおう")
    ふかみどり: Color = colorfield("#00552E", "ふかみどり")
    あんこうしょく: Color = colorfield("#74325C", "あんこうしょく")
    けんぽうくろちゃ: Color = colorfield("#241A08", "けんぽうくろちゃ")
    そほ: Color = colorfield("#AB6953", "そほ")
    こんじき: Color = colorfield("#E6B422", "こんじき")
    てついろ: Color = colorfield("#005243", "てついろ")
    くわのみいろ: Color = colorfield("#55295B", "くわのみいろ")
    あんこくしょく: Color = colorfield("#16160E", "あんこくしょく")
    SAKURAIRO: Color = colorfield("#FEF4F4", "SAKURAIRO")
    AZUKIIRO: Color = colorfield("#96514D", "AZUKIIRO")
    KOGANE: Color = colorfield("#E6B422", "KOGANE")
    MOEGIIRO: Color = colorfield("#006E54", "MOEGIIRO")
    KODAIMURASAKI: Color = colorfield("#895B8A", "KODAIMURASAKI")
    USUZAKURA: Color = colorfield("#FDEFF2", "USUZAKURA")
    KARACHA: Color = colorfield("#8D6449", "KARACHA")
    HAJIZOME: Color = colorfield("#D9A62E", "HAJIZOME")
    HANAROKUSHOU: Color = colorfield("#00A381", "HANAROKUSHOU")
    NASUKON: Color = colorfield("#824880", "NASUKON")
    SAKURANEZU: Color = colorfield("#E9DFE5", "SAKURANEZU")
    AMEIRO: Color = colorfield("#DEB068", "AMEIRO")
    KIKUCHIBAIRO: Color = colorfield("#D3A243", "KIKUCHIBAIRO")
    HISUIIRO: Color = colorfield("#38B48B", "HISUIIRO")
    FUTAAI: Color = colorfield("#915C8B", "FUTAAI")
    TOKINEZU: Color = colorfield("#E4D2D8", "TOKINEZU")
    RAKUDAIRO: Color = colorfield("#BF794E", "RAKUDAIRO")
    YAMABUKICHA: Color = colorfield("#C89932", "YAMABUKICHA")
    AOMIDORI: Color = colorfield("#00A497", "AOMIDORI")
    KYOUMURASAKI: Color = colorfield("#9D5B8B", "KYOUMURASAKI")
    NIJIIRO: Color = colorfield("#F6BFBC", "NIJIIRO")
    TSUCHIIRO: Color = colorfield("#BC763C", "TSUCHIIRO")
    KARASHIIRO: Color = colorfield("#D0AF4C", "KARASHIIRO")
    MIZUASAGI: Color = colorfield("#80ABA9", "MIZUASAGI")
    EBIZOME: Color = colorfield("#7A4171", "EBIZOME")
    SANGOIRO: Color = colorfield("#F5B1AA", "SANGOIRO")
    KIGARACHA: Color = colorfield("#B98C46", "KIGARACHA")
    MAMEGARACHA: Color = colorfield("#8B968D", "MAMEGARACHA")
    SABIASAGI: Color = colorfield("#5C9291", "SABIASAGI")
    WAKAMURASAKI: Color = colorfield("#BC64A4", "WAKAMURASAKI")
    IKKONZOME: Color = colorfield("#F5B199", "IKKONZOME")
    KUWAZOME: Color = colorfield("#B79B5B", "KUWAZOME")
    KIKUJIN: Color = colorfield("#6E7955", "KIKUJIN")
    SEIHEKI: Color = colorfield("#478384", "SEIHEKI")
    BENIMURASAKI: Color = colorfield("#B44C97", "BENIMURASAKI")
    SHISHIIRO: Color = colorfield("#EFAB93", "SHISHIIRO")
    HAJIIRO: Color = colorfield("#B77B57", "HAJIIRO")
    YAMABATOIRO: Color = colorfield("#767C6B", "YAMABATOIRO")
    OMESHICHA: Color = colorfield("#43676B", "OMESHICHA")
    UMEMURASAKI: Color = colorfield("#AA4C8F", "UMEMURASAKI")
    KOUBAIIRO: Color = colorfield("#F2A0A1", "KOUBAIIRO")
    KITSURUBAMI: Color = colorfield("#B68D4C", "KITSURUBAMI")
    RIKYUUNEZUMI: Color = colorfield("#888E7E", "RIKYUUNEZUMI")
    MINATONEZUMI: Color = colorfield("#80989B", "MINATONEZUMI")
    AYAMEIRO: Color = colorfield("#CC7EB1", "AYAMEIRO")
    USUBENI: Color = colorfield("#F0908D", "USUBENI")
    CHOUJIZOME: Color = colorfield("#AD7D4C", "CHOUJIZOME")
    MIRUCHA: Color = colorfield("#5A544B", "MIRUCHA")
    KOURAINANDO: Color = colorfield("#2C4F54", "KOURAINANDO")
    BENIFUJIIRO: Color = colorfield("#CCA6BF", "BENIFUJIIRO")
    JINZAMOMI: Color = colorfield("#EE827C", "JINZAMOMI")
    KOUZOME: Color = colorfield("#AD7D4C", "KOUZOME")
    AIMIRUCHA: Color = colorfield("#56564B", "AIMIRUCHA")
    MOMOSHIOCHA: Color = colorfield("#1F3134", "MOMOSHIOCHA")
    ASAMURASAKI: Color = colorfield("#C4A3BF", "ASAMURASAKI")
    MOMOIRO: Color = colorfield("#F09199", "MOMOIRO")
    BIWACHA: Color = colorfield("#AE7C4F", "BIWACHA")
    AIKOBICHA: Color = colorfield("#555647", "AIKOBICHA")
    SABINEZU: Color = colorfield("#47585C", "SABINEZU")
    MURASAKISUISHOU: Color = colorfield("#E7E7EB", "MURASAKISUISHOU")
    TOKIIRO: Color = colorfield("#F4B3C2", "TOKIIRO")
    SHIKANCHA: Color = colorfield("#AD7E4E", "SHIKANCHA")
    SENSAICHA: Color = colorfield("#494A41", "SENSAICHA")
    SABITETSUONANDO: Color = colorfield("#485859", "SABITETSUONANDO")
    USUUMENEZU: Color = colorfield("#DCD6D9", "USUUMENEZU")
    NADESHIKOIRO: Color = colorfield("#EEBBCB", "NADESHIKOIRO")
    KOGAREKOU: Color = colorfield("#AE7C58", "KOGAREKOU")
    IWAICHA: Color = colorfield("#6B6F59", "IWAICHA")
    AINEZU: Color = colorfield("#6C848D", "AINEZU")
    AKATSUKINEZU: Color = colorfield("#D3CFD9", "AKATSUKINEZU")
    HAIUME: Color = colorfield("#E8D3C7", "HAIUME")
    KURUMIIRO: Color = colorfield("#A86F4C", "KURUMIIRO")
    SENSAICHA: Color = colorfield("#474B42", "SENSAICHA")
    SABIONANDO: Color = colorfield("#53727D", "SABIONANDO")
    BOTANNEZU: Color = colorfield("#D3CCD6", "BOTANNEZU")
    HAIZAKURA: Color = colorfield("#E8D3D1", "HAIZAKURA")
    SHIBUKAMIIRO: Color = colorfield("#946243", "SHIBUKAMIIRO")
    KUROMIDORI: Color = colorfield("#333631", "KUROMIDORI")
    MASUHANAIRO: Color = colorfield("#5B7E91", "MASUHANAIRO")
    KASUMIIRO: Color = colorfield("#C8C2C6", "KASUMIIRO")
    AWABENIFUJI: Color = colorfield("#E6CDE3", "AWABENIFUJI")
    KUCHIBAIRO: Color = colorfield("#917347", "KUCHIBAIRO")
    YANAGISUSUTAKE: Color = colorfield("#5B6356", "YANAGISUSUTAKE")
    NOSHIMEHANAIRO: Color = colorfield("#426579", "NOSHIMEHANAIRO")
    FUJINEZU: Color = colorfield("#A6A5C4", "FUJINEZU")
    SEKICHIKUIRO: Color = colorfield("#E5ABBE", "SEKICHIKUIRO")
    KUWACHA: Color = colorfield("#956F29", "KUWACHA")
    KABACHAIRO: Color = colorfield("#726250", "KABACHAIRO")
    OMESHIONANDO: Color = colorfield("#4C6473", "OMESHIONANDO")
    HASHITAIRO: Color = colorfield("#A69ABD", "HASHITAIRO")
    USUKOUBAI: Color = colorfield("#E597B2", "USUKOUBAI")
    ROKOUCHA: Color = colorfield("#8C7042", "ROKOUCHA")
    UTSUBUSHIIRO: Color = colorfield("#9D896C", "UTSUBUSHIIRO")
    TETSUONANDO: Color = colorfield("#455765", "TETSUONANDO")
    USUIRO: Color = colorfield("#A89DAC", "USUIRO")
    MOMOHANAIRO: Color = colorfield("#E198B4", "MOMOHANAIRO")
    KOKUBOUSHOKU: Color = colorfield("#7B6C3E", "KOKUBOUSHOKU")
    NAMAKABEIRO: Color = colorfield("#94846A", "NAMAKABEIRO")
    KONNEZU: Color = colorfield("#44617B", "KONNEZU")
    USUNEZU: Color = colorfield("#9790A4", "USUNEZU")
    MIZUGAKI: Color = colorfield("#E4AB9B", "MIZUGAKI")
    KYARAIRO: Color = colorfield("#D8A373", "KYARAIRO")
    HIGOSUSUTAKE: Color = colorfield("#897858", "HIGOSUSUTAKE")
    AITETSU: Color = colorfield("#393F4C", "AITETSU")
    HATOBANEZUMI: Color = colorfield("#9E8B8E", "HATOBANEZUMI")
    TOKIGARACHA: Color = colorfield("#E09E87", "TOKIGARACHA")
    EDOCHA: Color = colorfield("#CD8C5C", "EDOCHA")
    KOBICHA: Color = colorfield("#716246", "KOBICHA")
    AOKACHI: Color = colorfield("#393E4F", "AOKACHI")
    HATOBAIRO: Color = colorfield("#95859C", "HATOBAIRO")
    ARAZOME: Color = colorfield("#D69090", "ARAZOME")
    KABAIRO: Color = colorfield("#CD5E3C", "KABAIRO")
    SHIROTSURUBAMI: Color = colorfield("#CBB994", "SHIROTSURUBAMI")
    KACHIKAESHI: Color = colorfield("#203744", "KACHIKAESHI")
    KIKYOUNEZU: Color = colorfield("#95949A", "KIKYOUNEZU")
    USUGAKI: Color = colorfield("#D4ACAD", "USUGAKI")
    BENIUKON: Color = colorfield("#CB8347", "BENIUKON")
    AMAIRO: Color = colorfield("#D6C6AF", "AMAIRO")
    KACHIIRO: Color = colorfield("#4D4C61", "KACHIIRO")
    MURASAKINEZU: Color = colorfield("#71686C", "MURASAKINEZU")
    CHOUSHUNNIRO: Color = colorfield("#C97586", "CHOUSHUNNIRO")
    KAWARAKEIRO: Color = colorfield("#C37854", "KAWARAKEIRO")
    HASHIBAMIIRO: Color = colorfield("#BFA46F", "HASHIBAMIIRO")
    GEPPAKU: Color = colorfield("#EAF4FC", "GEPPAKU")
    BUDOUNEZUMI: Color = colorfield("#705B67", "BUDOUNEZUMI")
    UMENEZU: Color = colorfield("#C099A0", "UMENEZU")
    KITSUNEIRO: Color = colorfield("#C38743", "KITSUNEIRO")
    AKUIRO: Color = colorfield("#9E9478", "AKUIRO")
    SHIROSUMIREIRO: Color = colorfield("#EAEDF7", "SHIROSUMIREIRO")
    KOKIIRO: Color = colorfield("#634950", "KOKIIRO")
    TOKIASAGI: Color = colorfield("#B88884", "TOKIASAGI")
    OUDOIRO: Color = colorfield("#C39143", "OUDOIRO")
    RIKYUUCHA: Color = colorfield("#A59564", "RIKYUUCHA")
    SHIRAHANAIRO: Color = colorfield("#E8ECEF", "SHIRAHANAIRO")
    MURASAKITOBI: Color = colorfield("#5F414B", "MURASAKITOBI")
    UMEZOME: Color = colorfield("#B48A76", "UMEZOME")
    KOHAKUIRO: Color = colorfield("#BF783A", "KOHAKUIRO")
    UGUISUCHA: Color = colorfield("#715C1F", "UGUISUCHA")
    AIJIRO: Color = colorfield("#EBF6F7", "AIJIRO")
    KOINEZU: Color = colorfield("#4F455C", "KOINEZU")
    SUOUKOU: Color = colorfield("#A86965", "SUOUKOU")
    AKACHA: Color = colorfield("#BB5535", "AKACHA")
    MOKURANJIKI: Color = colorfield("#C7B370", "MOKURANJIKI")
    SHIRAAI: Color = colorfield("#C1E4E9", "SHIRAAI")
    FUJISUSUTAKE: Color = colorfield("#5A5359", "FUJISUSUTAKE")
    ASASUOU: Color = colorfield("#A25768", "ASASUOU")
    TAISHA: Color = colorfield("#BB5520", "TAISHA")
    SUNAIRO: Color = colorfield("#DCD3B2", "SUNAIRO")
    MIZUIRO: Color = colorfield("#BCE2E8", "MIZUIRO")
    KESHIMURASAKI: Color = colorfield("#594255", "KESHIMURASAKI")
    MASOO: Color = colorfield("#EC6D71", "MASOO")
    RENGAIRO: Color = colorfield("#B55233", "RENGAIRO")
    ABURAIRO: Color = colorfield("#A19361", "ABURAIRO")
    KAMENOZOKI: Color = colorfield("#A2D7DD", "KAMENOZOKI")
    BENIKESHINEZUMI: Color = colorfield("#524748", "BENIKESHINEZUMI")
    AKAMURASAKI: Color = colorfield("#EB6EA5", "AKAMURASAKI")
    SUZUMECHA: Color = colorfield("#AA4F37", "SUZUMECHA")
    RIKYUUIRO: Color = colorfield("#8F8667", "RIKYUUIRO")
    HISOKUIRO: Color = colorfield("#ABCED8", "HISOKUIRO")
    NISEMURASAKI: Color = colorfield("#513743", "NISEMURASAKI")
    TSUTSUJIIRO: Color = colorfield("#E95295", "TSUTSUJIIRO")
    DANJUUROUCHA: Color = colorfield("#9F563A", "DANJUUROUCHA")
    BAIKOUCHA: Color = colorfield("#887938", "BAIKOUCHA")
    SORAIRO: Color = colorfield("#A0D8EF", "SORAIRO")
    HAIKIMIDORI: Color = colorfield("#E6EAE3", "HAIKIMIDORI")
    BOTANNIRO: Color = colorfield("#E7609E", "BOTANNIRO")
    KAKISHIBUIRO: Color = colorfield("#9F563A", "KAKISHIBUIRO")
    RIKANCHA: Color = colorfield("#6A5D21", "RIKANCHA")
    WASURENAGUSAIRO: Color = colorfield("#89C3EB", "WASURENAGUSAIRO")
    SOBAKIRIIRO: Color = colorfield("#D4DCD6", "SOBAKIRIIRO")
    IMAYOUIRO: Color = colorfield("#D0576B", "IMAYOUIRO")
    BENITOBI: Color = colorfield("#9A493F", "BENITOBI")
    KIMIRUCHA: Color = colorfield("#918754", "KIMIRUCHA")
    AOFUJIIRO: Color = colorfield("#84A2D4", "AOFUJIIRO")
    USUKUMONEZU: Color = colorfield("#D4DCDA", "USUKUMONEZU")
    NAKABENI: Color = colorfield("#C85179", "NAKABENI")
    HAICHA: Color = colorfield("#98623C", "HAICHA")
    NATANEYUIRO: Color = colorfield("#A69425", "NATANEYUIRO")
    BYAKUGUN: Color = colorfield("#83CCD2", "BYAKUGUN")
    KARENOIRO: Color = colorfield("#D3CBC6", "KARENOIRO")
    BARAIRO: Color = colorfield("#E9546B", "BARAIRO")
    CHAIRO: Color = colorfield("#965042", "CHAIRO")
    AOKUCHIBA: Color = colorfield("#ADA250", "AOKUCHIBA")
    ASAHANADA: Color = colorfield("#84B9CB", "ASAHANADA")
    URUMIIRO: Color = colorfield("#C8C2BE", "URUMIIRO")
    KARAKURENAI: Color = colorfield("#E95464", "KARAKURENAI")
    HIWADAIRO: Color = colorfield("#965036", "HIWADAIRO")
    NEGISHIIRO: Color = colorfield("#938B4B", "NEGISHIIRO")
    USUHANAIRO: Color = colorfield("#698AAB", "USUHANAIRO")
    RIKYUUSHIROCHA: Color = colorfield("#B3ADA0", "RIKYUUSHIROCHA")
    GINSHU: Color = colorfield("#C85554", "GINSHU")
    TOBIIRO: Color = colorfield("#95483F", "TOBIIRO")
    HIWACHA: Color = colorfield("#8C8861", "HIWACHA")
    NANDOIRO: Color = colorfield("#008899", "NANDOIRO")
    CHANEZUMI: Color = colorfield("#A99E93", "CHANEZUMI")
    AKABENI: Color = colorfield("#C53D43", "AKABENI")
    KAKICHA: Color = colorfield("#954E2A", "KAKICHA")
    YANAGICHA: Color = colorfield("#A1A46D", "YANAGICHA")
    ASAGIIRO: Color = colorfield("#00A3AF", "ASAGIIRO")
    KURUMIZOME: Color = colorfield("#A58F86", "KURUMIZOME")
    BENIHI: Color = colorfield("#E83929", "BENIHI")
    BENGARAIRO: Color = colorfield("#8F2E14", "BENGARAIRO")
    MIRUIRO: Color = colorfield("#726D40", "MIRUIRO")
    HANAASAGI: Color = colorfield("#2A83A2", "HANAASAGI")
    EDONEZU: Color = colorfield("#928178", "EDONEZU")
    AKA: Color = colorfield("#E60033", "AKA")
    AKASABIIRO: Color = colorfield("#8A3319", "AKASABIIRO")
    UGUISUIRO: Color = colorfield("#928C36", "UGUISUIRO")
    SHINBASHIIRO: Color = colorfield("#59B9C6", "SHINBASHIIRO")
    SUSUIRO: Color = colorfield("#887F7A", "SUSUIRO")
    SHOUJOUHI: Color = colorfield("#E2041B", "SHOUJOUHI")
    KASSHOKU: Color = colorfield("#8A3B00", "KASSHOKU")
    RYOKUOUSHOKU: Color = colorfield("#DCCB18", "RYOKUOUSHOKU")
    AMAIRO: Color = colorfield("#2CA9E1", "AMAIRO")
    CHOUJICHA: Color = colorfield("#B4866B", "CHOUJICHA")
    KURENAI: Color = colorfield("#D7003A", "KURENAI")
    KURIUME: Color = colorfield("#852E19", "KURIUME")
    HIWAIRO: Color = colorfield("#D7CF3A", "HIWAIRO")
    TSUYUKUSAIRO: Color = colorfield("#38A1DB", "TSUYUKUSAIRO")
    FUSHIZOME: Color = colorfield("#B28C6E", "FUSHIZOME")
    KOKIHI: Color = colorfield("#C9171E", "KOKIHI")
    BENIHIHADA: Color = colorfield("#7B4741", "BENIHIHADA")
    MATCHAIRO: Color = colorfield("#C5C56A", "MATCHAIRO")
    AO: Color = colorfield("#0095D9", "AO")
    SOUDENKARACHA: Color = colorfield("#A16D5D", "SOUDENKARACHA")
    HIIRO: Color = colorfield("#D3381C", "HIIRO")
    EBICHA: Color = colorfield("#773C30", "EBICHA")
    WAKAKUSAIRO: Color = colorfield("#C3D825", "WAKAKUSAIRO")
    USUAI: Color = colorfield("#0094C8", "USUAI")
    TONOCHA: Color = colorfield("#9F6F55", "TONOCHA")
    AKANI: Color = colorfield("#CE5242", "AKANI")
    KARACHA: Color = colorfield("#783C1D", "KARACHA")
    KIMIDORI: Color = colorfield("#B8D200", "KIMIDORI")
    HANADAIRO: Color = colorfield("#2792C3", "HANADAIRO")
    SENCHAIRO: Color = colorfield("#8C6450", "SENCHAIRO")
    BENIAKA: Color = colorfield("#D9333F", "BENIAKA")
    KURIIRO: Color = colorfield("#762F07", "KURIIRO")
    WAKAMEIRO: Color = colorfield("#E0EBAF", "WAKAMEIRO")
    KONPEKI: Color = colorfield("#007BBB", "KONPEKI")
    GINSUSUDAKE: Color = colorfield("#856859", "GINSUSUDAKE")
    ENJI: Color = colorfield("#B94047", "ENJI")
    SHAKUDOUIRO: Color = colorfield("#752100", "SHAKUDOUIRO")
    WAKANAIRO: Color = colorfield("#D8E698", "WAKANAIRO")
    USUGUNJOU: Color = colorfield("#5383C3", "USUGUNJOU")
    KIGARACHA: Color = colorfield("#765C47", "KIGARACHA")
    AKE: Color = colorfield("#BA2636", "AKE")
    SABIIRO: Color = colorfield("#6C3524", "SABIIRO")
    WAKANAEIRO: Color = colorfield("#C7DC68", "WAKANAEIRO")
    USUHANAZAKURA: Color = colorfield("#5A79BA", "USUHANAZAKURA")
    SUSUTAKEIRO: Color = colorfield("#6F514C", "SUSUTAKEIRO")
    AKANEIRO: Color = colorfield("#B7282E", "AKANEIRO")
    SEKKASSHOKU: Color = colorfield("#683F36", "SEKKASSHOKU")
    AONI: Color = colorfield("#99AB4E", "AONI")
    GUNJOUIRO: Color = colorfield("#4C6CB3", "GUNJOUIRO")
    KOGECHA: Color = colorfield("#6F4B3E", "KOGECHA")
    BENIEBICHA: Color = colorfield("#A73836", "BENIEBICHA")
    CHAKASSHOKU: Color = colorfield("#664032", "CHAKASSHOKU")
    KUSAIRO: Color = colorfield("#7B8D42", "KUSAIRO")
    KAKITSUBATAIRO: Color = colorfield("#3E62AD", "KAKITSUBATAIRO")
    KUROTSURUBAMI: Color = colorfield("#544A47", "KUROTSURUBAMI")
    SUOU: Color = colorfield("#9E3D3F", "SUOU")
    KURIKAWACHA: Color = colorfield("#6D3C32", "KURIKAWACHA")
    KOKEIRO: Color = colorfield("#69821B", "KOKEIRO")
    RURIIRO: Color = colorfield("#1E50A2", "RURIIRO")
    KENPOUIRO: Color = colorfield("#543F32", "KENPOUIRO")
    SHINKU: Color = colorfield("#A22041", "SHINKU")
    KUROCHA: Color = colorfield("#583822", "KUROCHA")
    MOEGI: Color = colorfield("#AACF53", "MOEGI")
    USUHANADA: Color = colorfield("#507EA4", "USUHANADA")
    KURIIRO: Color = colorfield("#554738", "KURIIRO")
    KOIKURENAI: Color = colorfield("#A22041", "KOIKURENAI")
    EBICHA: Color = colorfield("#6C2C2F", "EBICHA")
    NAEIRO: Color = colorfield("#B0CA71", "NAEIRO")
    RURIKON: Color = colorfield("#19448E", "RURIKON")
    BINROUJIZOME: Color = colorfield("#433D3C", "BINROUJIZOME")
    ZOUGEIRO: Color = colorfield("#F8F4E6", "ZOUGEIRO")
    EBIIRO: Color = colorfield("#640125", "EBIIRO")
    WAKABAIRO: Color = colorfield("#B9D08B", "WAKABAIRO")
    KONRURI: Color = colorfield("#164A84", "KONRURI")
    KUROTOBI: Color = colorfield("#432F2F", "KUROTOBI")
    NERIIRO: Color = colorfield("#EDE4CD", "NERIIRO")
    KANZOUIRO: Color = colorfield("#F8B862", "KANZOUIRO")
    MATSUBAIRO: Color = colorfield("#839B5C", "MATSUBAIRO")
    AIIRO: Color = colorfield("#165E83", "AIIRO")
    AKASUMI: Color = colorfield("#3F312B", "AKASUMI")
    KAIHAKUSHOKU: Color = colorfield("#E9E4D4", "KAIHAKUSHOKU")
    KOUJIIRO: Color = colorfield("#F6AD49", "KOUJIIRO")
    NATSUMUSHIIRO: Color = colorfield("#CEE4AE", "NATSUMUSHIIRO")
    SEIRAN: Color = colorfield("#274A78", "SEIRAN")
    KUROBENI: Color = colorfield("#302833", "KUROBENI")
    MUSHIGURIIRO: Color = colorfield("#EBE1A9", "MUSHIGURIIRO")
    KINCHA: Color = colorfield("#F39800", "KINCHA")
    HIWAMOEGI: Color = colorfield("#82AE46", "HIWAMOEGI")
    KOKIHANADA: Color = colorfield("#2A4073", "KOKIHANADA")
    SHIRO: Color = colorfield("#FFFFFF", "SHIRO")
    OMINAESHI: Color = colorfield("#F2F2B0", "OMINAESHI")
    MIKANNIRO: Color = colorfield("#F08300", "MIKANNIRO")
    YANAGIIRO: Color = colorfield("#A8C97F", "YANAGIIRO")
    KONNIRO: Color = colorfield("#223A70", "KONNIRO")
    GOFUNNIRO: Color = colorfield("#FFFFFC", "GOFUNNIRO")
    KAREKUSAIRO: Color = colorfield("#E4DC8A", "KAREKUSAIRO")
    ENTANNIRO: Color = colorfield("#EC6D51", "ENTANNIRO")
    AOSHIROTSURUBAMI: Color = colorfield("#9BA88D", "AOSHIROTSURUBAMI")
    KONJOU: Color = colorfield("#192F60", "KONJOU")
    UNOHANAIRO: Color = colorfield("#F7FCFE", "UNOHANAIRO")
    TANKOU: Color = colorfield("#F8E58C", "TANKOU")
    OUNI: Color = colorfield("#EE7948", "OUNI")
    YANAGINEZU: Color = colorfield("#C8D5BB", "YANAGINEZU")
    TOMEKON: Color = colorfield("#1C305C", "TOMEKON")
    HAKUJI: Color = colorfield("#F8FBF8", "HAKUJI")
    SHIRACHA: Color = colorfield("#DDBB99", "SHIRACHA")
    KAKIIRO: Color = colorfield("#ED6D3D", "KAKIIRO")
    URAHAYANAGI: Color = colorfield("#C1D8AC", "URAHAYANAGI")
    KOIAI: Color = colorfield("#0F2350", "KOIAI")
    KINARIIRO: Color = colorfield("#FBFAF5", "KINARIIRO")
    AKASHIROTSURUBAMI: Color = colorfield("#D7A98C", "AKASHIROTSURUBAMI")
    KIAKA: Color = colorfield("#EC6800", "KIAKA")
    WASABIIRO: Color = colorfield("#A8BF93", "WASABIIRO")
    TETSUKON: Color = colorfield("#17184B", "TETSUKON")
    NYUUHAKUSHOKU: Color = colorfield("#F3F3F3", "NYUUHAKUSHOKU")
    ARAIGAKI: Color = colorfield("#F2C9AC", "ARAIGAKI")
    NINJINNIRO: Color = colorfield("#EC6800", "NINJINNIRO")
    OITAKEIRO: Color = colorfield("#769164", "OITAKEIRO")
    SHIKKOKU: Color = colorfield("#0D0015", "SHIKKOKU")
    SHIRONERI: Color = colorfield("#F3F3F2", "SHIRONERI")
    TORINOKOIRO: Color = colorfield("#FFF1CF", "TORINOKOIRO")
    DAIDAIIRO: Color = colorfield("#EE7800", "DAIDAIIRO")
    BYAKUROKU: Color = colorfield("#D6E9CA", "BYAKUROKU")
    AWAFUJIIRO: Color = colorfield("#BBC8E6", "AWAFUJIIRO")
    SOSHOKU: Color = colorfield("#EAE5E3", "SOSHOKU")
    HACHIMITSUIRO: Color = colorfield("#FDDEA5", "HACHIMITSUIRO")
    TERIGAKI: Color = colorfield("#EB6238", "TERIGAKI")
    USUMOEGI: Color = colorfield("#93CA76", "USUMOEGI")
    FUJIIRO: Color = colorfield("#BBBCDE", "FUJIIRO")
    SHIRAUMENEZU: Color = colorfield("#E5E4E6", "SHIRAUMENEZU")
    HADAIRO: Color = colorfield("#FCE2C4", "HADAIRO")
    AKADAIDAI: Color = colorfield("#EA5506", "AKADAIDAI")
    YANAGIZOME: Color = colorfield("#93B881", "YANAGIZOME")
    BENIKAKESORAIRO: Color = colorfield("#8491C3", "BENIKAKESORAIRO")
    SHIRONEZU: Color = colorfield("#DCDDDD", "SHIRONEZU")
    USUTAMAGOIRO: Color = colorfield("#FDE8D0", "USUTAMAGOIRO")
    KINNAKA: Color = colorfield("#EA5506", "KINNAKA")
    USUMOEGI: Color = colorfield("#BADCAD", "USUMOEGI")
    BENIMIDORI: Color = colorfield("#8491C3", "BENIMIDORI")
    KINUNEZU: Color = colorfield("#DDDCD6", "KINUNEZU")
    YUUOU: Color = colorfield("#F9C89B", "YUUOU")
    SHUIRO: Color = colorfield("#EB6101", "SHUIRO")
    FUKAGAWANEZUMI: Color = colorfield("#97A791", "FUKAGAWANEZUMI")
    KONKIKYOU: Color = colorfield("#4D5AAF", "KONKIKYOU")
    HAIAO: Color = colorfield("#C0C6C9", "HAIAO")
    SHAREGAKI: Color = colorfield("#F7BD8F", "SHAREGAKI")
    KOMUGIIRO: Color = colorfield("#E49E61", "KOMUGIIRO")
    WAKAMIDORI: Color = colorfield("#98D98E", "WAKAMIDORI")
    HANAIRO: Color = colorfield("#4D5AAF", "HANAIRO")
    GINNEZU: Color = colorfield("#AFAFB0", "GINNEZU")
    AKAKOU: Color = colorfield("#F6B894", "AKAKOU")
    NIIRO: Color = colorfield("#E45E32", "NIIRO")
    ASAMIDORI: Color = colorfield("#88CB7F", "ASAMIDORI")
    KONNAI: Color = colorfield("#4A488E", "KONNAI")
    USUNIBI: Color = colorfield("#ADADAD", "USUNIBI")
    TONOKOIRO: Color = colorfield("#F4DDA5", "TONOKOIRO")
    KICHA: Color = colorfield("#E17B34", "KICHA")
    USUMIDORI: Color = colorfield("#69B076", "USUMIDORI")
    BENIKIKYOU: Color = colorfield("#4D4398", "BENIKIKYOU")
    USUZUMIIRO: Color = colorfield("#A3A3A2", "USUZUMIIRO")
    NIKUIRO: Color = colorfield("#F1BF99", "NIKUIRO")
    NIKKEIIRO: Color = colorfield("#DD7A56", "NIKKEIIRO")
    AONIBI: Color = colorfield("#6B7B6E", "AONIBI")
    KIKYOUIRO: Color = colorfield("#5654A2", "KIKYOUIRO")
    SUZUIRO: Color = colorfield("#9EA1A3", "SUZUIRO")
    HITOIRO: Color = colorfield("#F1BF99", "HITOIRO")
    AKAKUCHIBAIRO: Color = colorfield("#DB8449", "AKAKUCHIBAIRO")
    SEIJINEZU: Color = colorfield("#BED2C3", "SEIJINEZU")
    FUJINANDO: Color = colorfield("#706CAA", "FUJINANDO")
    SUNEZUMI: Color = colorfield("#9FA0A0", "SUNEZUMI")
    CHOUJIIRO: Color = colorfield("#EFCD9A", "CHOUJIIRO")
    KOUROZEN: Color = colorfield("#D66A35", "KOUROZEN")
    USUAO: Color = colorfield("#93B69C", "USUAO")
    BENIKAKEHANAIRO: Color = colorfield("#68699B", "BENIKAKEHANAIRO")
    NEZUMIIRO: Color = colorfield("#949495", "NEZUMIIRO")
    KOUIRO: Color = colorfield("#EFCD9A", "KOUIRO")
    TANPOPOIRO: Color = colorfield("#FFD900", "TANPOPOIRO")
    SABISEIJI: Color = colorfield("#A6C8B2", "SABISEIJI")
    SHIONNIRO: Color = colorfield("#867BA9", "SHIONNIRO")
    GENJINEZU: Color = colorfield("#888084", "GENJINEZU")
    USUKOU: Color = colorfield("#F0CFA0", "USUKOU")
    KIIRO: Color = colorfield("#FFD900", "KIIRO")
    ROKUSHOUIRO: Color = colorfield("#47885E", "ROKUSHOUIRO")
    SHIRAFUJIIRO: Color = colorfield("#DBD0E6", "SHIRAFUJIIRO")
    HAIIRO: Color = colorfield("#7D7D7D", "HAIIRO")
    USUKI: Color = colorfield("#EDD3A1", "USUKI")
    CHUUKI: Color = colorfield("#FFEA00", "CHUUKI")
    CHITOSEMIDORI: Color = colorfield("#316745", "CHITOSEMIDORI")
    FUJIMURASAKI: Color = colorfield("#A59ACA", "FUJIMURASAKI")
    NAMARIIRO: Color = colorfield("#7B7C7D", "NAMARIIRO")
    KAREIRO: Color = colorfield("#E0C38C", "KAREIRO")
    NANOHANAIRO: Color = colorfield("#FFEC47", "NANOHANAIRO")
    WAKATAKEIRO: Color = colorfield("#68BE8D", "WAKATAKEIRO")
    SUMIREIRO: Color = colorfield("#7058A3", "SUMIREIRO")
    NIBIIRO: Color = colorfield("#727171", "NIBIIRO")
    USUKOU: Color = colorfield("#F3BF88", "USUKOU")
    KIHADAIRO: Color = colorfield("#FEF263", "KIHADAIRO")
    MIDORI: Color = colorfield("#3EB370", "MIDORI")
    AOMURASAKI: Color = colorfield("#674598", "AOMURASAKI")
    SUMI: Color = colorfield("#595857", "SUMI")
    ANZUIRO: Color = colorfield("#F7B977", "ANZUIRO")
    TAMAGOIRO: Color = colorfield("#FCD575", "TAMAGOIRO")
    TOKIWAIRO: Color = colorfield("#007B43", "TOKIWAIRO")
    SHOUBUIRO: Color = colorfield("#674196", "SHOUBUIRO")
    DOBUNEZUMI: Color = colorfield("#595455", "DOBUNEZUMI")
    SHINONOMEIRO: Color = colorfield("#F19072", "SHINONOMEIRO")
    HANABAIRO: Color = colorfield("#FBD26B", "HANABAIRO")
    CHIGUSANEZU: Color = colorfield("#BED3CA", "CHIGUSANEZU")
    RINDOUIRO: Color = colorfield("#9079AD", "RINDOUIRO")
    KESHIZUMIIRO: Color = colorfield("#524E4D", "KESHIZUMIIRO")
    AKEBONOIRO: Color = colorfield("#F19072", "AKEBONOIRO")
    KARIYASUIRO: Color = colorfield("#F5E56B", "KARIYASUIRO")
    CHIGUSAIRO: Color = colorfield("#92B5A9", "CHIGUSAIRO")
    EDOMURASAKI: Color = colorfield("#745399", "EDOMURASAKI")
    AISUMICHA: Color = colorfield("#474A4D", "AISUMICHA")
    SANGOSHUIRO: Color = colorfield("#EE836F", "SANGOSHUIRO")
    TOUMOROKOSHIIRO: Color = colorfield("#EEC362", "TOUMOROKOSHIIRO")
    SEIJIIRO: Color = colorfield("#7EBEA5", "SEIJIIRO")
    HONMURASAKI: Color = colorfield("#65318E", "HONMURASAKI")
    YOUKANNIRO: Color = colorfield("#383C3C", "YOUKANNIRO")
    KOKIKUCHINASHI: Color = colorfield("#EB9B6F", "KOKIKUCHINASHI")
    KANARIAIRO: Color = colorfield("#EBD842", "KANARIAIRO")
    AOTAKEIRO: Color = colorfield("#7EBEAB", "AOTAKEIRO")
    BUDOUIRO: Color = colorfield("#522F60", "BUDOUIRO")
    ROUIRO: Color = colorfield("#2B2B2B", "ROUIRO")
    SOHI: Color = colorfield("#E0815E", "SOHI")
    KIKUCHINASHIIRO: Color = colorfield("#FFDB4F", "KIKUCHINASHIIRO")
    TOKIWAMIDORI: Color = colorfield("#028760", "TOKIWAMIDORI")
    FUKAMURASAKI: Color = colorfield("#493759", "FUKAMURASAKI")
    KURO: Color = colorfield("#2B2B2B", "KURO")
    USUKIHI: Color = colorfield("#DF7163", "USUKIHI")
    KUCHINASHIIRO: Color = colorfield("#FBCA4D", "KUCHINASHIIRO")
    TOKUSAIRO: Color = colorfield("#3B7960", "TOKUSAIRO")
    SHIKOKU: Color = colorfield("#2E2930", "SHIKOKU")
    KARASUBAIRO: Color = colorfield("#180614", "KARASUBAIRO")
    MASOHO: Color = colorfield("#D57C6B", "MASOHO")
    HIMAWARIIRO: Color = colorfield("#FCC800", "HIMAWARIIRO")
    BIROUDO: Color = colorfield("#2F5D50", "BIROUDO")
    MURASAKI: Color = colorfield("#884898", "MURASAKI")
    TETSUGURO: Color = colorfield("#281A14", "TETSUGURO")
    ARAISHU: Color = colorfield("#D0826C", "ARAISHU")
    YAMABUKIIRO: Color = colorfield("#F8B500", "YAMABUKIIRO")
    MUSHIAO: Color = colorfield("#3A5B52", "MUSHIAO")
    USUBUDOU: Color = colorfield("#C0A2C7", "USUBUDOU")
    NUREBAIRO: Color = colorfield("#000B00", "NUREBAIRO")
    ENSHUUCHA: Color = colorfield("#CA8269", "ENSHUUCHA")
    UKONNIRO: Color = colorfield("#FABF14", "UKONNIRO")
    KAWAIRO: Color = colorfield("#475950", "KAWAIRO")
    SHIKON: Color = colorfield("#460E44", "SHIKON")
    KOKUTAN: Color = colorfield("#250D00", "KOKUTAN")
    BENIKABAIRO: Color = colorfield("#BB5548", "BENIKABAIRO")
    TOUOU: Color = colorfield("#F7C114", "TOUOU")
    FUKAMIDORI: Color = colorfield("#00552E", "FUKAMIDORI")
    ANKOUSHOKU: Color = colorfield("#74325C", "ANKOUSHOKU")
    KENPOUKUROCHA: Color = colorfield("#241A08", "KENPOUKUROCHA")
    SOHO: Color = colorfield("#AB6953", "SOHO")
    KONJIKI: Color = colorfield("#E6B422", "KONJIKI")
    TETSUIRO: Color = colorfield("#005243", "TETSUIRO")
    KUWANOMIIRO: Color = colorfield("#55295B", "KUWANOMIIRO")
    ANKOKUSHOKU: Color = colorfield("#16160E", "ANKOKUSHOKU")

    裏葉色: Color = colorfield("#A4C2A9", "裏葉色")
    うらはいろ: Color = colorfield("#A4C2A9", "うらはいろ")
    URAHAIRO: Color = colorfield("#A4C2A9", "URAHAIRO")

    小鴨色: Color = colorfield("#006263", "小鴨色")
    こがもいろ: Color = colorfield("#006263", "こがもいろ")
    KOGAMOIRO: Color = colorfield("#006263", "KOGAMOIRO")

    藁色: Color = colorfield("#D5C752", "藁色")
    わらいろ: Color = colorfield("#D5C752", "わらいろ")
    WARAIRO: Color = colorfield("#D5C752", "WARAIRO")

    @staticmethod
    def search(name: str) -> Color:
        """Search color by name
        Args:
            name (str): color name
        Returns:
            Color: color object
        Raises:
            AttributeError: if color not found

        Examples:
        >>> JapaneseColorCode.search("朱緋")
        Color("朱緋", RGB:(186, 38, 54), HEX:#BA2636)

        >>> JapaneseColorCode.search("わかば")
        Color("わかばいろ", RGB:(185, 208, 139), HEX:#B9D08B)

        >>> JapaneseColorCode.search("sakura")
        AttributeError: Color 'sakura' is ambiguous, candidates are ['SAKURAIRO', 'SAKURANEZU']
        """
        if getattr(JapaneseColorCode, name, None):
            return getattr(JapaneseColorCode, name)
        else:
            candidate = []
            for slot in JapaneseColorCode.__slots__:
                if name.lower() in slot.lower():
                    candidate.append(slot)
            if len(candidate) == 1:
                return getattr(JapaneseColorCode, candidate[0])
            elif len(candidate) > 1:
                raise AttributeError(f"Color '{name}' is ambiguous, candidates are {candidate}")
            raise AttributeError(f"Color '{name}' not found")


JP_COLOR_CODE = JapaneseColorCode()


@dataclass(frozen=True, slots=True)
class ColorTheme:
    name: str
    colors: tuple[Color, ...] = field(default_factory=tuple)
    length: int = field(init=False)

    def __post_init__(self):
        object.__setattr__(self, "length", len(self.colors))

    def __len__(self) -> int:
        return self.length

    def __getitem__(self, key: int) -> Color:
        return self.colors[key]

    def __iter__(self) -> Iterator[Color]:
        return iter(self.colors)

    def __str__(self) -> str:
        return f"ColorTheme(name={self.name}, colors={','.join(map(lambda x: str(ColoredStr(str(x.name), fg=x)), self))})"


@dataclass(frozen=True, slots=True)
class JapaneseColorTheme:
    春: ColorTheme = ColorTheme(
        "春",
        (
            JP_COLOR_CODE.桜色,
            JP_COLOR_CODE.若葉色,
            JP_COLOR_CODE.紅梅色,
            JP_COLOR_CODE.柳茶,
            JP_COLOR_CODE.菜の花色,
            JP_COLOR_CODE.青藤色,
        ),
    )
    夏: ColorTheme = ColorTheme(
        "夏",
        (
            JP_COLOR_CODE.浅葱色,
            JP_COLOR_CODE.若竹色,
            JP_COLOR_CODE.萱草色,
            JP_COLOR_CODE.露草色,
            JP_COLOR_CODE.小鴨色,
            JP_COLOR_CODE.杜若色,
            JP_COLOR_CODE.菖蒲色,
        ),
    )
    秋: ColorTheme = ColorTheme(
        "秋",
        (
            JP_COLOR_CODE.茜色,
            JP_COLOR_CODE.深支子,
            JP_COLOR_CODE.竜胆色,
            JP_COLOR_CODE.柿色,
            JP_COLOR_CODE.栗皮茶,
            JP_COLOR_CODE.群青色,
        ),
    )
    冬: ColorTheme = ColorTheme(
        "冬",
        (
            JP_COLOR_CODE.銀鼠,
            JP_COLOR_CODE.消炭色,
            JP_COLOR_CODE.薄香,
            JP_COLOR_CODE.千歳緑,
            JP_COLOR_CODE.朱色,
            JP_COLOR_CODE.藁色,
        ),
    )

    def __iter__(self) -> Iterator[ColorTheme]:
        return iter((getattr(self, name) for name in self.__slots__))


JP_COLOR_THEME = JapaneseColorTheme()
